// HSK 3 (Band 3) vocabulary — 500 words from the official 词汇大纲 (HSK 考试大纲).
// Hanzi, pinyin, and part-of-speech are taken directly from the syllabus PDF (序号 501–1000).
// English glosses and example sentences are study aids authored for this course.
// Each entry: [hanzi, pinyin, pos, english, example_hanzi, example_pinyin, example_english]
window.BAND3_WORDS = [
  ["阿姨", "āyí", "n.", "aunt; nanny", "我家请了一位阿姨。", "Wǒ jiā qǐng le yí wèi āyí.", "My family hired a nanny."],
  ["矮", "ǎi", "adj.", "short (height)", "他个子很矮。", "Tā gèzi hěn ǎi.", "He is very short."],
  ["爱人", "àiren", "n.", "spouse", "这是我的爱人。", "Zhè shì wǒ de àiren.", "This is my spouse."],
  ["安静", "ānjìng", "adj.", "quiet; peaceful", "图书馆里很安静。", "Túshūguǎn lǐ hěn ānjìng.", "The library is very quiet."],
  ["安全", "ānquán", "adj.", "safe; secure", "开车要注意安全。", "Kāichē yào zhùyì ānquán.", "Be careful and safe when driving."],
  ["把", "bǎ", "mw./prep.", "measure word; ba-particle", "请把门关上。", "Qǐng bǎ mén guānshàng.", "Please close the door."],
  ["搬", "bān", "v.", "to move; carry", "我们帮他搬桌子。", "Wǒmen bāng tā bān zhuōzi.", "We help him move the table."],
  ["班级", "bānjí", "n.", "class (school)", "我们班级有很多学生。", "Wǒmen bānjí yǒu hěn duō xuésheng.", "Our class has many students."],
  ["搬家", "bānjiā", "v.", "to move house", "他们下个月搬家。", "Tāmen xià ge yuè bānjiā.", "They are moving house next month."],
  ["办", "bàn", "v.", "to handle; do", "这件事我来办。", "Zhè jiàn shì wǒ lái bàn.", "I will handle this matter."],
  ["办法", "bànfǎ", "n.", "method; way", "这是个好办法。", "Zhè shì ge hǎo bànfǎ.", "This is a good method."],
  ["办公室", "bàngōngshì", "n.", "office", "老师在办公室里。", "Lǎoshī zài bàngōngshì lǐ.", "The teacher is in the office."],
  ["半天", "bàntiān", "num.+mw.", "half a day; a long while", "我等了你半天。", "Wǒ děng le nǐ bàntiān.", "I waited for you a long while."],
  ["帮助", "bāngzhù", "v.", "to help; assist", "谢谢你的帮助。", "Xièxie nǐ de bāngzhù.", "Thank you for your help."],
  ["饱", "bǎo", "adj.", "full (eaten)", "我吃饱了。", "Wǒ chī bǎo le.", "I am full."],
  ["报纸", "bàozhǐ", "n.", "newspaper", "爸爸在看报纸。", "Bàba zài kàn bàozhǐ.", "Dad is reading the newspaper."],
  ["北", "běi", "n.", "north", "往北走就到了。", "Wǎng běi zǒu jiù dào le.", "Walk north and you'll arrive."],
  ["北方", "běifāng", "n.", "the north", "北方的冬天很冷。", "Běifāng de dōngtiān hěn lěng.", "Winters in the north are cold."],
  ["被", "bèi", "prep.", "by (passive marker)", "杯子被他打破了。", "Bēizi bèi tā dǎpò le.", "The cup was broken by him."],
  ["笔记", "bǐjì", "n.", "notes", "上课要记笔记。", "Shàngkè yào jì bǐjì.", "Take notes during class."],
  ["比较", "bǐjiào", "v./prep./adv.", "compare; relatively", "今天比较冷。", "Jīntiān bǐjiào lěng.", "It is relatively cold today."],
  ["笔记本", "bǐjìběn", "n.", "notebook", "我买了一个笔记本。", "Wǒ mǎi le yí ge bǐjìběn.", "I bought a notebook."],
  ["比如", "bǐrú", "v.", "for example", "我喜欢水果，比如苹果。", "Wǒ xǐhuan shuǐguǒ, bǐrú píngguǒ.", "I like fruit, for example apples."],
  ["比赛", "bǐsài", "v./n.", "match; competition", "今天有足球比赛。", "Jīntiān yǒu zúqiú bǐsài.", "There is a football match today."],
  ["必须", "bìxū", "adv.", "must; have to", "你必须按时来。", "Nǐ bìxū ànshí lái.", "You must come on time."],
  ["变", "biàn", "v.", "to change", "天气变冷了。", "Tiānqì biàn lěng le.", "The weather has turned cold."],
  ["遍", "biàn", "mw.", "time (frequency)", "请再说一遍。", "Qǐng zài shuō yí biàn.", "Please say it once more."],
  ["变成", "biànchéng", "v.", "to become; turn into", "小树变成了大树。", "Xiǎo shù biànchéng le dà shù.", "The small tree became a big tree."],
  ["变化", "biànhuà", "v./n.", "change", "城市的变化很大。", "Chéngshì de biànhuà hěn dà.", "The city has changed a lot."],
  ["表演", "biǎoyǎn", "v.", "to perform", "他们在台上表演。", "Tāmen zài tái shàng biǎoyǎn.", "They are performing on stage."],
  ["别的", "biéde", "pron.", "other; else", "还有别的问题吗？", "Hái yǒu biéde wèntí ma?", "Are there any other questions?"],
  ["别人", "biérén", "pron.", "other people", "别人都走了。", "Biérén dōu zǒu le.", "Everyone else has left."],
  ["宾馆", "bīnguǎn", "n.", "hotel", "我们住在宾馆里。", "Wǒmen zhù zài bīnguǎn lǐ.", "We are staying in a hotel."],
  ["冰", "bīng", "n.", "ice", "河里有很多冰。", "Hé lǐ yǒu hěn duō bīng.", "There is a lot of ice in the river."],
  ["冰激凌", "bīngjīlíng", "n.", "ice cream", "孩子们爱吃冰激凌。", "Háizimen ài chī bīngjīlíng.", "Children love eating ice cream."],
  ["冰箱", "bīngxiāng", "n.", "refrigerator", "牛奶在冰箱里。", "Niúnǎi zài bīngxiāng lǐ.", "The milk is in the refrigerator."],
  ["病人", "bìngrén", "n.", "patient; sick person", "医生在照顾病人。", "Yīshēng zài zhàogù bìngrén.", "The doctor is caring for the patient."],
  ["不但", "búdàn", "conj.", "not only", "他不但聪明，而且努力。", "Tā búdàn cōngmíng, érqiě nǔlì.", "He is not only smart but also hardworking."],
  ["不见", "bújiàn", "v.", "to disappear; not see", "我的钥匙不见了。", "Wǒ de yàoshi bújiàn le.", "My keys have disappeared."],
  ["不用", "búyòng", "adv.", "need not", "不用谢。", "Búyòng xiè.", "You're welcome (no need to thank)."],
  ["不同", "bùtóng", "adj.", "different", "我们的想法不同。", "Wǒmen de xiǎngfǎ bùtóng.", "Our ideas are different."],
  ["不久", "bùjiǔ", "adj.", "soon; before long", "他不久就回来了。", "Tā bùjiǔ jiù huílái le.", "He came back before long."],
  ["不行", "bùxíng", "v./adj.", "won't do; no good", "这样做不行。", "Zhèyàng zuò bùxíng.", "Doing it this way won't work."],
  ["才", "cái", "adv.", "only then; just", "他现在才到。", "Tā xiànzài cái dào.", "He only arrived just now."],
  ["菜单", "càidān", "n.", "menu", "服务员给我菜单。", "Fúwùyuán gěi wǒ càidān.", "The waiter gave me the menu."],
  ["参加", "cānjiā", "v.", "to participate; attend", "我想参加比赛。", "Wǒ xiǎng cānjiā bǐsài.", "I want to take part in the competition."],
  ["草", "cǎo", "n.", "grass", "草地上的草很绿。", "Cǎodì shàng de cǎo hěn lǜ.", "The grass on the lawn is very green."],
  ["草地", "cǎodì", "n.", "lawn; grassland", "孩子们在草地上玩。", "Háizimen zài cǎodì shàng wán.", "The children play on the lawn."],
  ["层", "céng", "mw.", "floor; layer", "我家在三层。", "Wǒ jiā zài sān céng.", "My home is on the third floor."],
  ["查", "chá", "v.", "to check; look up", "请查一下这个词。", "Qǐng chá yíxià zhège cí.", "Please look up this word."],
  ["差", "chà", "adj./v.", "poor; lacking", "他的成绩很差。", "Tā de chéngjì hěn chà.", "His grades are very poor."],
  ["差不多", "chàbuduō", "adj./adv.", "almost; about the same", "我们差不多到了。", "Wǒmen chàbuduō dào le.", "We have almost arrived."],
  ["尝", "cháng", "v.", "to taste", "你尝尝这个菜。", "Nǐ chángchang zhège cài.", "Taste this dish."],
  ["常", "cháng", "adv.", "often", "我常去那家店。", "Wǒ cháng qù nà jiā diàn.", "I often go to that shop."],
  ["常见", "chángjiàn", "adj.", "common", "这是个常见的问题。", "Zhè shì ge chángjiàn de wèntí.", "This is a common problem."],
  ["常用", "chángyòng", "adj.", "commonly used", "这是常用的词。", "Zhè shì chángyòng de cí.", "This is a commonly used word."],
  ["常常", "chángcháng", "adv.", "often; frequently", "他常常迟到。", "Tā chángcháng chídào.", "He is often late."],
  ["衬衫", "chènshān", "n.", "shirt", "这件衬衫很好看。", "Zhè jiàn chènshān hěn hǎokàn.", "This shirt looks very nice."],
  ["成绩", "chéngjì", "n.", "grades; achievement", "她的成绩很好。", "Tā de chéngjì hěn hǎo.", "Her grades are very good."],
  ["城市", "chéngshì", "n.", "city", "北京是个大城市。", "Běijīng shì ge dà chéngshì.", "Beijing is a big city."],
  ["迟到", "chídào", "v.", "to be late", "上学不要迟到。", "Shàngxué búyào chídào.", "Don't be late for school."],
  ["出发", "chūfā", "v.", "to set off; depart", "我们明天早上出发。", "Wǒmen míngtiān zǎoshang chūfā.", "We set off tomorrow morning."],
  ["出生", "chūshēng", "v.", "to be born", "她在北京出生。", "Tā zài Běijīng chūshēng.", "She was born in Beijing."],
  ["出院", "chūyuàn", "v.", "leave hospital", "病人明天出院。", "Bìngrén míngtiān chūyuàn.", "The patient leaves the hospital tomorrow."],
  ["初中", "chūzhōng", "n.", "junior high school", "我弟弟上初中。", "Wǒ dìdi shàng chūzhōng.", "My younger brother is in junior high."],
  ["除了", "chúle", "prep.", "except; besides", "除了他，大家都来了。", "Chúle tā, dàjiā dōu lái le.", "Everyone came except him."],
  ["船", "chuán", "n.", "boat; ship", "我们坐船去对岸。", "Wǒmen zuò chuán qù duì'àn.", "We take a boat to the other shore."],
  ["春天", "chūntiān", "n.", "spring (season)", "春天花都开了。", "Chūntiān huā dōu kāi le.", "In spring all the flowers bloom."],
  ["词典", "cídiǎn", "n.", "dictionary", "我用词典查生词。", "Wǒ yòng cídiǎn chá shēngcí.", "I use a dictionary to look up new words."],
  ["聪明", "cōngmíng", "adj.", "smart; clever", "这个孩子很聪明。", "Zhège háizi hěn cōngmíng.", "This child is very smart."],
  ["打扫", "dǎsǎo", "v.", "to clean; sweep", "我每天打扫房间。", "Wǒ měitiān dǎsǎo fángjiān.", "I clean my room every day."],
  ["打算", "dǎsuàn", "v./n.", "to plan; intend", "你打算去哪里？", "Nǐ dǎsuàn qù nǎlǐ?", "Where do you plan to go?"],
  ["大概", "dàgài", "adj./adv.", "probably; approximately", "他大概八点到。", "Tā dàgài bā diǎn dào.", "He'll probably arrive at eight."],
  ["大人", "dàren", "n.", "adult", "这个电影适合大人看。", "Zhège diànyǐng shìhé dàren kàn.", "This movie is suitable for adults."],
  ["大小", "dàxiǎo", "n.", "size", "这双鞋大小正合适。", "Zhè shuāng xié dàxiǎo zhèng héshì.", "This pair of shoes is just the right size."],
  ["大熊猫", "dàxióngmāo", "n.", "giant panda", "大熊猫爱吃竹子。", "Dàxióngmāo ài chī zhúzi.", "Giant pandas love eating bamboo."],
  ["大衣", "dàyī", "n.", "overcoat", "天冷了，穿上大衣。", "Tiān lěng le, chuān shàng dàyī.", "It's cold, put on your overcoat."],
  ["带", "dài", "v.", "to bring; carry", "别忘了带雨伞。", "Bié wàng le dài yǔsǎn.", "Don't forget to bring an umbrella."],
  ["担心", "dānxīn", "v.", "to worry", "妈妈很担心我。", "Māma hěn dānxīn wǒ.", "Mom worries about me a lot."],
  ["蛋糕", "dàngāo", "n.", "cake", "生日要吃蛋糕。", "Shēngrì yào chī dàngāo.", "You eat cake on your birthday."],
  ["当然", "dāngrán", "adv.", "of course", "我当然愿意帮你。", "Wǒ dāngrán yuànyì bāng nǐ.", "Of course I'm willing to help you."],
  ["到处", "dàochù", "adv.", "everywhere", "春天到处是花。", "Chūntiān dàochù shì huā.", "In spring there are flowers everywhere."],
  ["得", "dé", "v.", "to get; obtain", "他得了第一名。", "Tā dé le dì-yī míng.", "He got first place."],
  ["得到", "dédào", "v.", "to obtain; receive", "她得到了大家的帮助。", "Tā dédào le dàjiā de bāngzhù.", "She received everyone's help."],
  ["得分", "défēn", "v./n.", "to score; points", "这场比赛他得分最多。", "Zhè chǎng bǐsài tā défēn zuì duō.", "He scored the most in this match."],
  ["的话", "dehuà", "part.", "if (clause marker)", "有问题的话就问我。", "Yǒu wèntí dehuà jiù wèn wǒ.", "If you have questions, just ask me."],
  ["得", "děi", "v.", "must; have to", "我得走了。", "Wǒ děi zǒu le.", "I have to go now."],
  ["灯", "dēng", "n.", "lamp; light", "请把灯打开。", "Qǐng bǎ dēng dǎkāi.", "Please turn on the light."],
  ["地", "dì", "n.", "ground; land", "地上很干净。", "Dì shàng hěn gānjìng.", "The ground is very clean."],
  ["地点", "dìdiǎn", "n.", "location; place", "开会的地点变了。", "Kāihuì de dìdiǎn biàn le.", "The meeting location has changed."],
  ["地方", "dìfang", "n.", "place", "这个地方很美。", "Zhège dìfang hěn měi.", "This place is beautiful."],
  ["地图", "dìtú", "n.", "map", "我们看看地图吧。", "Wǒmen kànkan dìtú ba.", "Let's look at the map."],
  ["电", "diàn", "n.", "electricity", "家里没电了。", "Jiā lǐ méi diàn le.", "There's no electricity at home."],
  ["电梯", "diàntī", "n.", "elevator; lift", "我们坐电梯上去。", "Wǒmen zuò diàntī shàngqù.", "We take the elevator up."],
  ["电子书", "diànzǐshū", "n.", "e-book", "我喜欢看电子书。", "Wǒ xǐhuan kàn diànzǐshū.", "I like reading e-books."],
  ["丢", "diū", "v.", "to lose; throw", "我把手机丢了。", "Wǒ bǎ shǒujī diū le.", "I lost my phone."],
  ["东", "dōng", "n.", "east", "太阳从东边升起。", "Tàiyáng cóng dōngbiān shēngqǐ.", "The sun rises in the east."],
  ["东北", "dōngběi", "n.", "northeast", "他来自东北。", "Tā láizì dōngběi.", "He comes from the northeast."],
  ["东方", "dōngfāng", "n.", "the east; Orient", "东方文化很有意思。", "Dōngfāng wénhuà hěn yǒuyìsi.", "Eastern culture is very interesting."],
  ["东南", "dōngnán", "n.", "southeast", "风从东南方来。", "Fēng cóng dōngnán fāng lái.", "The wind comes from the southeast."],
  ["冬天", "dōngtiān", "n.", "winter", "冬天很冷。", "Dōngtiān hěn lěng.", "Winter is very cold."],
  ["懂得", "dǒngde", "v.", "understand; know", "他懂得这个道理。", "Tā dǒngde zhège dàolǐ.", "He understands this principle."],
  ["动物", "dòngwù", "n.", "animal", "我喜欢动物。", "Wǒ xǐhuan dòngwù.", "I like animals."],
  ["动物园", "dòngwùyuán", "n.", "zoo", "我们去动物园吧。", "Wǒmen qù dòngwùyuán ba.", "Let's go to the zoo."],
  ["短", "duǎn", "adj.", "short", "这条裤子太短了。", "Zhè tiáo kùzi tài duǎn le.", "These pants are too short."],
  ["短裤", "duǎnkù", "n.", "shorts", "夏天我穿短裤。", "Xiàtiān wǒ chuān duǎnkù.", "In summer I wear shorts."],
  ["段", "duàn", "mw.", "section; paragraph", "请读这一段。", "Qǐng dú zhè yí duàn.", "Please read this paragraph."],
  ["锻炼", "duànliàn", "v.", "exercise; work out", "我每天早上锻炼。", "Wǒ měitiān zǎoshang duànliàn.", "I exercise every morning."],
  ["对话", "duìhuà", "v.", "dialogue; converse", "请听这段对话。", "Qǐng tīng zhè duàn duìhuà.", "Please listen to this dialogue."],
  ["饿", "è", "adj.", "hungry", "我现在很饿。", "Wǒ xiànzài hěn è.", "I am very hungry now."],
  ["而且", "érqiě", "conj.", "moreover; and", "她聪明而且努力。", "Tā cōngmíng érqiě nǔlì.", "She is smart and hardworking."],
  ["耳朵", "ěrduo", "n.", "ear", "兔子的耳朵很长。", "Tùzi de ěrduo hěn cháng.", "The rabbit's ears are long."],
  ["耳机", "ěrjī", "n.", "earphones", "他戴着耳机听歌。", "Tā dàizhe ěrjī tīng gē.", "He listens to songs with earphones."],
  ["发", "fā", "v.", "send; issue", "我给你发一条信息。", "Wǒ gěi nǐ fā yì tiáo xìnxī.", "I'll send you a message."],
  ["发烧", "fāshāo", "v.", "have a fever", "孩子昨天发烧了。", "Háizi zuótiān fāshāo le.", "The child had a fever yesterday."],
  ["发生", "fāshēng", "v.", "happen; occur", "这里发生了什么？", "Zhèlǐ fāshēng le shénme?", "What happened here?"],
  ["发现", "fāxiàn", "v.", "discover; find", "我发现了一个问题。", "Wǒ fāxiàn le yí ge wèntí.", "I discovered a problem."],
  ["发展", "fāzhǎn", "v.", "develop; grow", "这座城市发展很快。", "Zhè zuò chéngshì fāzhǎn hěn kuài.", "This city develops very fast."],
  ["方便", "fāngbiàn", "adj.", "convenient", "坐地铁很方便。", "Zuò dìtiě hěn fāngbiàn.", "Taking the subway is convenient."],
  ["方便面", "fāngbiànmiàn", "n.", "instant noodles", "晚上我吃了方便面。", "Wǎnshang wǒ chī le fāngbiànmiàn.", "I ate instant noodles in the evening."],
  ["方法", "fāngfǎ", "n.", "method; way", "这个方法很好。", "Zhège fāngfǎ hěn hǎo.", "This method is good."],
  ["方向", "fāngxiàng", "n.", "direction", "我走错了方向。", "Wǒ zǒucuò le fāngxiàng.", "I went in the wrong direction."],
  ["房子", "fángzi", "n.", "house", "他们买了新房子。", "Tāmen mǎi le xīn fángzi.", "They bought a new house."],
  ["放", "fàng", "v.", "put; place", "把书放在桌子上。", "Bǎ shū fàng zài zhuōzi shàng.", "Put the book on the table."],
  ["放假", "fàngjià", "v.", "have a holiday", "我们明天放假。", "Wǒmen míngtiān fàngjià.", "We have a holiday tomorrow."],
  ["放心", "fàngxīn", "v.", "feel at ease", "你放心，没问题。", "Nǐ fàngxīn, méi wèntí.", "Don't worry, no problem."],
  ["放学", "fàngxué", "v.", "finish school", "我们三点放学。", "Wǒmen sān diǎn fàngxué.", "We finish school at three."],
  ["分开", "fēnkāi", "v.", "separate; part", "他们分开住。", "Tāmen fēnkāi zhù.", "They live separately."],
  ["风", "fēng", "n.", "wind", "今天风很大。", "Jīntiān fēng hěn dà.", "The wind is strong today."],
  ["封", "fēng", "mw./v.", "measure word for letters", "我收到一封信。", "Wǒ shōudào yì fēng xìn.", "I received a letter."],
  ["夫妻", "fūqī", "n.", "husband and wife", "他们是一对夫妻。", "Tāmen shì yí duì fūqī.", "They are a married couple."],
  ["服务", "fúwù", "v.", "serve; service", "这家店服务很好。", "Zhè jiā diàn fúwù hěn hǎo.", "This shop has good service."],
  ["附近", "fùjìn", "n.", "nearby; vicinity", "附近有一家超市。", "Fùjìn yǒu yì jiā chāoshì.", "There is a supermarket nearby."],
  ["复习", "fùxí", "v.", "review; revise", "考试前我要复习。", "Kǎoshì qián wǒ yào fùxí.", "I need to review before the exam."],
  ["该", "gāi", "v.", "should; ought to", "你该睡觉了。", "Nǐ gāi shuìjiào le.", "You should go to sleep."],
  ["干净", "gānjìng", "adj.", "clean", "房间很干净。", "Fángjiān hěn gānjìng.", "The room is very clean."],
  ["感兴趣", "gǎn xìngqù", "v.", "be interested in", "我对音乐感兴趣。", "Wǒ duì yīnyuè gǎn xìngqù.", "I am interested in music."],
  ["感到", "gǎndào", "v.", "feel; sense", "我感到很开心。", "Wǒ gǎndào hěn kāixīn.", "I feel very happy."],
  ["感冒", "gǎnmào", "n./v.", "cold; catch a cold", "我感冒了。", "Wǒ gǎnmào le.", "I caught a cold."],
  ["干", "gàn", "v.", "do; work", "你在干什么？", "Nǐ zài gàn shénme?", "What are you doing?"],
  ["刚", "gāng", "adv.", "just; just now", "他刚走。", "Tā gāng zǒu.", "He just left."],
  ["刚才", "gāngcái", "n.", "just now; a moment ago", "刚才谁来了？", "Gāngcái shéi lái le?", "Who came just now?"],
  ["刚刚", "gānggāng", "adv.", "just; a moment ago", "我刚刚到家。", "Wǒ gānggāng dào jiā.", "I just got home."],
  ["高铁", "gāotiě", "n.", "high-speed rail", "我坐高铁去北京。", "Wǒ zuò gāotiě qù Běijīng.", "I take the high-speed rail to Beijing."],
  ["根据", "gēnjù", "v./prep.", "according to; based on", "根据天气，我们改了计划。", "Gēnjù tiānqì, wǒmen gǎi le jìhuà.", "Based on the weather, we changed the plan."],
  ["更", "gèng", "adv.", "more; even more", "今天比昨天更热。", "Jīntiān bǐ zuótiān gèng rè.", "Today is even hotter than yesterday."],
  ["公斤", "gōngjīn", "mw.", "kilogram", "我买了两公斤苹果。", "Wǒ mǎi le liǎng gōngjīn píngguǒ.", "I bought two kilograms of apples."],
  ["公园", "gōngyuán", "n.", "park", "我们去公园散步。", "Wǒmen qù gōngyuán sànbù.", "We go for a walk in the park."],
  ["工作日", "gōngzuòrì", "n.", "workday; weekday", "工作日我很忙。", "Gōngzuòrì wǒ hěn máng.", "I am busy on workdays."],
  ["故事", "gùshi", "n.", "story", "妈妈给我讲故事。", "Māma gěi wǒ jiǎng gùshi.", "Mom tells me a story."],
  ["刮", "guā", "v.", "blow; scrape", "外面刮风了。", "Wàimiàn guā fēng le.", "It's windy outside."],
  ["关", "guān", "v./n.", "close; shut", "请关门。", "Qǐng guān mén.", "Please close the door."],
  ["关机", "guānjī", "v.", "turn off (a device)", "上课时请关机。", "Shàngkè shí qǐng guānjī.", "Please turn off your phone during class."],
  ["关系", "guānxì", "n./v.", "relationship", "他们的关系很好。", "Tāmen de guānxì hěn hǎo.", "Their relationship is good."],
  ["关心", "guānxīn", "v.", "care about", "她很关心家人。", "Tā hěn guānxīn jiārén.", "She cares about her family."],
  ["关于", "guānyú", "prep.", "about; regarding", "这是一本关于历史的书。", "Zhè shì yì běn guānyú lìshǐ de shū.", "This is a book about history."],
  ["关注", "guānzhù", "v.", "follow; pay attention to", "我关注了这个账号。", "Wǒ guānzhù le zhège zhànghào.", "I followed this account."],
  ["国家", "guójiā", "n.", "country; nation", "中国是一个大国家。", "Zhōngguó shì yí ge dà guójiā.", "China is a big country."],
  ["过节", "guòjié", "v.", "celebrate a festival", "我们回家过节。", "Wǒmen huí jiā guòjié.", "We go home to celebrate the festival."],
  ["过去", "guòqù", "n.", "the past", "过去的事别再想了。", "Guòqù de shì bié zài xiǎng le.", "Don't think about the past anymore."],
  ["海", "hǎi", "n.", "sea", "我喜欢看海。", "Wǒ xǐhuan kàn hǎi.", "I like looking at the sea."],
  ["害怕", "hàipà", "v.", "be afraid; fear", "她害怕黑暗。", "Tā hàipà hēi'àn.", "She is afraid of the dark."],
  ["好多", "hǎoduō", "num.", "a lot of; many", "门口有好多人。", "Ménkǒu yǒu hǎoduō rén.", "There are a lot of people at the door."],
  ["好久", "hǎojiǔ", "adj.", "a long time", "好久不见！", "Hǎojiǔ bú jiàn!", "Long time no see!"],
  ["好像", "hǎoxiàng", "v./adv.", "seem; as if", "他好像生病了。", "Tā hǎoxiàng shēngbìng le.", "He seems to be sick."],
  ["号码", "hàomǎ", "n.", "number", "请告诉我你的电话号码。", "Qǐng gàosu wǒ nǐ de diànhuà hàomǎ.", "Please tell me your phone number."],
  ["河", "hé", "n.", "river", "这条河很长。", "Zhè tiáo hé hěn cháng.", "This river is very long."],
  ["合适", "héshì", "adj.", "suitable; fitting", "这件衣服很合适。", "Zhè jiàn yīfu hěn héshì.", "This piece of clothing fits well."],
  ["黑板", "hēibǎn", "n.", "blackboard", "老师在黑板上写字。", "Lǎoshī zài hēibǎn shàng xiě zì.", "The teacher writes on the blackboard."],
  ["红绿灯", "hóng-lǜdēng", "n.", "traffic light", "前面有一个红绿灯。", "Qiánmiàn yǒu yí ge hóng-lǜdēng.", "There is a traffic light ahead."],
  ["后来", "hòulái", "n.", "later; afterwards", "后来他怎么样了？", "Hòulái tā zěnmeyàng le?", "What happened to him later?"],
  ["后年", "hòunián", "n.", "the year after next", "后年我要毕业。", "Hòunián wǒ yào bìyè.", "I will graduate the year after next."],
  ["后天", "hòutiān", "n.", "the day after tomorrow", "后天是我的生日。", "Hòutiān shì wǒ de shēngrì.", "The day after tomorrow is my birthday."],
  ["护照", "hùzhào", "n.", "passport", "别忘了带护照。", "Bié wàng le dài hùzhào.", "Don't forget to bring your passport."],
  ["花园", "huāyuán", "n.", "garden", "花园里有很多花。", "Huāyuán lǐ yǒu hěn duō huā.", "There are many flowers in the garden."],
  ["画家", "huàjiā", "n.", "painter; artist", "他是一位有名的画家。", "Tā shì yí wèi yǒumíng de huàjiā.", "He is a famous painter."],
  ["欢迎", "huānyíng", "v.", "welcome", "欢迎你来我家。", "Huānyíng nǐ lái wǒ jiā.", "Welcome to my home."],
  ["还", "huán", "v.", "return; give back", "我明天还你书。", "Wǒ míngtiān huán nǐ shū.", "I'll return your book tomorrow."],
  ["环境", "huánjìng", "n.", "environment", "这里的环境很好。", "Zhèlǐ de huánjìng hěn hǎo.", "The environment here is very good."],
  ["换", "huàn", "v.", "change; exchange", "我想换一个房间。", "Wǒ xiǎng huàn yí ge fángjiān.", "I'd like to change rooms."],
  ["黄色", "huángsè", "n.", "yellow (color)", "她喜欢黄色的花。", "Tā xǐhuan huángsè de huā.", "She likes yellow flowers."],
  ["回答", "huídá", "v.", "to answer; reply", "请回答我的问题。", "Qǐng huídá wǒ de wèntí.", "Please answer my question."],
  ["会", "huì", "n.", "meeting; gathering", "今天下午有一个会。", "Jīntiān xiàwǔ yǒu yí ge huì.", "There is a meeting this afternoon."],
  ["会议", "huìyì", "n.", "meeting; conference", "会议明天开始。", "Huìyì míngtiān kāishǐ.", "The conference starts tomorrow."],
  ["或", "huò", "conj./adv.", "or", "你或我去都行。", "Nǐ huò wǒ qù dōu xíng.", "Either you or I can go."],
  ["或者", "huòzhě", "conj.", "or; either", "喝茶或者咖啡都可以。", "Hē chá huòzhě kāfēi dōu kěyǐ.", "Tea or coffee is fine."],
  ["鸡", "jī", "n.", "chicken", "院子里有几只鸡。", "Yuànzi lǐ yǒu jǐ zhī jī.", "There are a few chickens in the yard."],
  ["几乎", "jīhū", "adv.", "almost; nearly", "我几乎每天都跑步。", "Wǒ jīhū měi tiān dōu pǎobù.", "I run almost every day."],
  ["机会", "jīhuì", "n.", "opportunity; chance", "这是一个好机会。", "Zhè shì yí ge hǎo jīhuì.", "This is a good opportunity."],
  ["极", "jí", "adv.", "extremely; very", "今天热极了。", "Jīntiān rè jí le.", "It is extremely hot today."],
  ["急", "jí", "adj./v.", "anxious; urgent", "别急，慢慢来。", "Bié jí, mànman lái.", "Don't worry, take your time."],
  ["记", "jì", "v.", "to remember; record", "我记不住他的名字。", "Wǒ jì bú zhù tā de míngzi.", "I can't remember his name."],
  ["季", "jì", "n.", "season", "一年有四季。", "Yì nián yǒu sì jì.", "A year has four seasons."],
  ["季节", "jìjié", "n.", "season", "春天是我最喜欢的季节。", "Chūntiān shì wǒ zuì xǐhuan de jìjié.", "Spring is my favorite season."],
  ["加", "jiā", "v.", "to add; plus", "请给我加点水。", "Qǐng gěi wǒ jiā diǎn shuǐ.", "Please add some water for me."],
  ["假期", "jiàqī", "n.", "holiday; vacation", "假期我想去旅游。", "Jiàqī wǒ xiǎng qù lǚyóu.", "I want to travel during the holiday."],
  ["坚持", "jiānchí", "v.", "to persist; insist", "他坚持每天学习。", "Tā jiānchí měi tiān xuéxí.", "He persists in studying every day."],
  ["检查", "jiǎnchá", "v.", "to check; examine", "医生给我检查了身体。", "Yīshēng gěi wǒ jiǎnchá le shēntǐ.", "The doctor examined my body."],
  ["简单", "jiǎndān", "adj.", "simple; easy", "这个问题很简单。", "Zhège wèntí hěn jiǎndān.", "This question is very simple."],
  ["检票", "jiǎnpiào", "v.", "to check tickets", "上车前要检票。", "Shàng chē qián yào jiǎnpiào.", "You must have your ticket checked before boarding."],
  ["健康", "jiànkāng", "adj.", "healthy; health", "他身体很健康。", "Tā shēntǐ hěn jiànkāng.", "He is very healthy."],
  ["见面", "jiànmiàn", "v.", "to meet; see", "我们明天见面。", "Wǒmen míngtiān jiànmiàn.", "We will meet tomorrow."],
  ["讲", "jiǎng", "v.", "to speak; tell", "老师在讲故事。", "Lǎoshī zài jiǎng gùshi.", "The teacher is telling a story."],
  ["角", "jiǎo", "mw.", "jiao (currency unit)", "这个五角钱。", "Zhège wǔ jiǎo qián.", "This costs five jiao."],
  ["脚", "jiǎo", "n.", "foot", "我的脚有点疼。", "Wǒ de jiǎo yǒudiǎn téng.", "My foot hurts a little."],
  ["接", "jiē", "v.", "to receive; pick up", "我去机场接朋友。", "Wǒ qù jīchǎng jiē péngyou.", "I'm going to the airport to pick up a friend."],
  ["街", "jiē", "n.", "street", "这条街很热闹。", "Zhè tiáo jiē hěn rènao.", "This street is very lively."],
  ["节", "jié", "mw./n./v.", "festival; section", "今天是一个重要的节日。", "Jīntiān shì yí ge zhòngyào de jiérì.", "Today is an important festival."],
  ["结婚", "jiéhūn", "v.", "to marry", "他们去年结婚了。", "Tāmen qùnián jiéhūn le.", "They got married last year."],
  ["节目", "jiémù", "n.", "program; show", "这个节目很有意思。", "Zhège jiémù hěn yǒu yìsi.", "This program is very interesting."],
  ["节日", "jiérì", "n.", "festival; holiday", "春节是中国的节日。", "Chūnjié shì Zhōngguó de jiérì.", "Spring Festival is a Chinese holiday."],
  ["结束", "jiéshù", "v.", "to end; finish", "会议已经结束了。", "Huìyì yǐjīng jiéshù le.", "The meeting has already ended."],
  ["解决", "jiějué", "v.", "to solve; resolve", "我们一起解决问题。", "Wǒmen yìqǐ jiějué wèntí.", "Let's solve the problem together."],
  ["姐妹", "jiěmèi", "n.", "sisters", "她们是姐妹。", "Tāmen shì jiěmèi.", "They are sisters."],
  ["借", "jiè", "v.", "to borrow; lend", "我想借一本书。", "Wǒ xiǎng jiè yì běn shū.", "I want to borrow a book."],
  ["斤", "jīn", "mw.", "jin (half kilo)", "我买了两斤苹果。", "Wǒ mǎi le liǎng jīn píngguǒ.", "I bought two jin of apples."],
  ["经过", "jīngguò", "v./n.", "to pass; process", "我每天经过这家商店。", "Wǒ měi tiān jīngguò zhè jiā shāngdiàn.", "I pass by this shop every day."],
  ["经理", "jīnglǐ", "n.", "manager", "他是我们的经理。", "Tā shì wǒmen de jīnglǐ.", "He is our manager."],
  ["久", "jiǔ", "adj.", "long (time)", "我们很久没见了。", "Wǒmen hěn jiǔ méi jiàn le.", "We haven't met for a long time."],
  ["酒", "jiǔ", "n.", "alcohol; wine", "他不喜欢喝酒。", "Tā bù xǐhuan hē jiǔ.", "He doesn't like to drink alcohol."],
  ["旧", "jiù", "adj.", "old; used", "这件衣服太旧了。", "Zhè jiàn yīfu tài jiù le.", "This piece of clothing is too old."],
  ["句", "jù", "mw.", "measure word for sentences", "请说一句中文。", "Qǐng shuō yí jù Zhōngwén.", "Please say a sentence in Chinese."],
  ["句子", "jùzi", "n.", "sentence", "这个句子很长。", "Zhège jùzi hěn cháng.", "This sentence is very long."],
  ["决定", "juédìng", "v./n.", "to decide; decision", "我决定明天出发。", "Wǒ juédìng míngtiān chūfā.", "I decided to set off tomorrow."],
  ["卡", "kǎ", "n.", "card", "我有一张银行卡。", "Wǒ yǒu yì zhāng yínháng kǎ.", "I have a bank card."],
  ["开花", "kāihuā", "v.", "to bloom; flower", "春天花都开花了。", "Chūntiān huā dōu kāihuā le.", "In spring the flowers all bloom."],
  ["开会", "kāihuì", "v.", "to hold a meeting", "我们下午开会。", "Wǒmen xiàwǔ kāihuì.", "We have a meeting in the afternoon."],
  ["开机", "kāijī", "v.", "to turn on (a device)", "请先开机。", "Qǐng xiān kāijī.", "Please turn on the device first."],
  ["开心", "kāixīn", "adj.", "happy; joyful", "今天我很开心。", "Jīntiān wǒ hěn kāixīn.", "I am very happy today."],
  ["看来", "kànlái", "v.", "it seems; apparently", "看来要下雨了。", "Kànlái yào xià yǔ le.", "It seems it's going to rain."],
  ["可", "kě", "conj./adv.", "but; however", "我想去，可没有时间。", "Wǒ xiǎng qù, kě méiyǒu shíjiān.", "I want to go, but I have no time."],
  ["渴", "kě", "adj.", "thirsty", "我有点渴。", "Wǒ yǒudiǎn kě.", "I'm a little thirsty."],
  ["可爱", "kě'ài", "adj.", "cute; lovely", "这只小猫很可爱。", "Zhè zhī xiǎo māo hěn kě'ài.", "This little cat is very cute."],
  ["可是", "kěshì", "conj.", "but; however", "我累了，可是很开心。", "Wǒ lèi le, kěshì hěn kāixīn.", "I'm tired, but very happy."],
  ["刻", "kè", "mw./v.", "quarter (hour); carve", "现在是三点一刻。", "Xiànzài shì sān diǎn yí kè.", "It's now a quarter past three."],
  ["课本", "kèběn", "n.", "textbook", "请打开课本。", "Qǐng dǎkāi kèběn.", "Please open your textbook."],
  ["客人", "kèrén", "n.", "guest; visitor", "今天家里来了客人。", "Jīntiān jiā lǐ lái le kèrén.", "Guests came to our home today."],
  ["课文", "kèwén", "n.", "text; lesson text", "今天的课文很难。", "Jīntiān de kèwén hěn nán.", "Today's text is very difficult."],
  ["空调", "kōngtiáo", "n.", "air conditioner", "房间里有空调。", "Fángjiān lǐ yǒu kōngtiáo.", "There is an air conditioner in the room."],
  ["哭", "kū", "v.", "to cry; weep", "孩子哭了起来。", "Háizi kū le qǐlái.", "The child started to cry."],
  ["筷子", "kuàizi", "n.", "chopsticks", "他会用筷子。", "Tā huì yòng kuàizi.", "He can use chopsticks."],
  ["矿泉水", "kuàngquánshuǐ", "n.", "mineral water", "请给我一瓶矿泉水。", "Qǐng gěi wǒ yì píng kuàngquánshuǐ.", "Please give me a bottle of mineral water."],
  ["来自", "láizì", "v.", "to come from", "他来自北京。", "Tā láizì Běijīng.", "He comes from Beijing."],
  ["蓝", "lán", "adj.", "blue", "天空很蓝。", "Tiānkōng hěn lán.", "The sky is very blue."],
  ["老", "lǎo", "adj./adv.", "old; aged", "我的爷爷很老了。", "Wǒ de yéye hěn lǎo le.", "My grandfather is very old."],
  ["老人", "lǎorén", "n.", "elderly person", "那位老人很和气。", "Nà wèi lǎorén hěn héqi.", "That elderly person is very kind."],
  ["离开", "líkāi", "v.", "to leave; depart", "他已经离开了。", "Tā yǐjīng líkāi le.", "He has already left."],
  ["礼物", "lǐwù", "n.", "gift; present", "这是给你的礼物。", "Zhè shì gěi nǐ de lǐwù.", "This is a gift for you."],
  ["历史", "lìshǐ", "n.", "history", "我喜欢学历史。", "Wǒ xǐhuan xué lìshǐ.", "I like studying history."],
  ["脸", "liǎn", "n.", "face", "她的脸红了。", "Tā de liǎn hóng le.", "Her face turned red."],
  ["练", "liàn", "v.", "to practice; train", "我每天练写字。", "Wǒ měi tiān liàn xiězì.", "I practice writing characters every day."],
  ["练习", "liànxí", "v./n.", "to practice; exercise", "请做这个练习。", "Qǐng zuò zhège liànxí.", "Please do this exercise."],
  ["凉快", "liángkuai", "adj.", "cool; pleasantly cool", "今天天气很凉快。", "Jīntiān tiānqì hěn liángkuai.", "The weather is pleasantly cool today."],
  ["辆", "liàng", "mw.", "measure word for vehicles", "门口有一辆车。", "Ménkǒu yǒu yí liàng chē.", "There is a car at the door."],
  ["聊", "liáo", "v.", "to chat", "我们聊了很久。", "Wǒmen liáo le hěn jiǔ.", "We chatted for a long time."],
  ["聊天儿", "liáotiānr", "v.", "to chat; chitchat", "她喜欢和朋友聊天儿。", "Tā xǐhuan hé péngyou liáotiānr.", "She likes to chat with friends."],
  ["了解", "liǎojiě", "v.", "to understand; know", "我想了解中国文化。", "Wǒ xiǎng liǎojiě Zhōngguó wénhuà.", "I want to understand Chinese culture."],
  ["邻居", "línjū", "n.", "neighbor", "我的邻居很友好。", "Wǒ de línjū hěn yǒuhǎo.", "My neighbor is very friendly."],
  ["留学", "liúxué", "v.", "to study abroad", "他想去美国留学。", "Tā xiǎng qù Měiguó liúxué.", "He wants to study abroad in the USA."],
  ["留学生", "liúxuéshēng", "n.", "international student", "她是一名留学生。", "Tā shì yì míng liúxuéshēng.", "She is an international student."],
  ["楼梯", "lóutī", "n.", "stairs; staircase", "他从楼梯走下来。", "Tā cóng lóutī zǒu xiàlái.", "He walked down the stairs."],
  ["路边", "lùbiān", "n.", "roadside", "路边有很多树。", "Lùbiān yǒu hěn duō shù.", "There are many trees by the roadside."],
  ["路口", "lùkǒu", "n.", "intersection; crossing", "在路口往右拐。", "Zài lùkǒu wǎng yòu guǎi.", "Turn right at the intersection."],
  ["马", "mǎ", "n.", "horse", "那匹马跑得很快。", "Nà pǐ mǎ pǎo de hěn kuài.", "That horse runs very fast."],
  ["马路", "mǎlù", "n.", "road; street", "过马路要小心。", "Guò mǎlù yào xiǎoxīn.", "Be careful crossing the road."],
  ["马上", "mǎshàng", "adv.", "at once; immediately", "我马上就来。", "Wǒ mǎshàng jiù lái.", "I'll come right away."],
  ["满意", "mǎnyì", "v.", "to be satisfied", "老板对结果很满意。", "Lǎobǎn duì jiéguǒ hěn mǎnyì.", "The boss is satisfied with the result."],
  ["毛", "máo", "mw./n.", "mao (currency); hair", "这个三毛钱。", "Zhège sān máo qián.", "This costs three mao."],
  ["米", "mǐ", "mw.", "meter (length)", "这条路有两百米长。", "Zhè tiáo lù yǒu liǎngbǎi mǐ cháng.", "This road is two hundred meters long."],
  ["面前", "miànqián", "n.", "in front of", "他站在我面前。", "Tā zhàn zài wǒ miànqián.", "He stood in front of me."],
  ["明白", "míngbai", "adj./v.", "clear; to understand", "我明白你的意思。", "Wǒ míngbai nǐ de yìsi.", "I understand what you mean."],
  ["名单", "míngdān", "n.", "name list", "请看一下名单。", "Qǐng kàn yíxià míngdān.", "Please take a look at the name list."],
  ["名人", "míngrén", "n.", "famous person", "他是一位名人。", "Tā shì yí wèi míngrén.", "He is a famous person."],
  ["南", "nán", "n.", "south", "我家在城南。", "Wǒ jiā zài chéng nán.", "My home is in the south of the city."],
  ["难", "nán", "adj./v.", "difficult; hard", "这道题很难。", "Zhè dào tí hěn nán.", "This problem is very difficult."],
  ["南方", "nánfāng", "n.", "the south", "南方的冬天不太冷。", "Nánfāng de dōngtiān bú tài lěng.", "Winters in the south are not very cold."],
  ["难过", "nánguò", "adj.", "sad; sorry", "听到这个消息我很难过。", "Tīngdào zhège xiāoxi wǒ hěn nánguò.", "I was sad to hear this news."],
  ["难看", "nánkàn", "adj.", "ugly; unsightly", "这件衣服很难看。", "Zhè jiàn yīfu hěn nánkàn.", "This piece of clothing is ugly."],
  ["男人", "nánrén", "n.", "man", "那个男人是我哥哥。", "Nàge nánrén shì wǒ gēge.", "That man is my older brother."],
  ["男生", "nánshēng", "n.", "male student; boy", "我们班有二十个男生。", "Wǒmen bān yǒu èrshí ge nánshēng.", "There are twenty boys in our class."],
  ["难题", "nántí", "n.", "difficult problem", "这是一个难题。", "Zhè shì yí ge nántí.", "This is a difficult problem."],
  ["难听", "nántīng", "adj.", "unpleasant to hear", "这首歌很难听。", "Zhè shǒu gē hěn nántīng.", "This song sounds unpleasant."],
  ["年级", "niánjí", "n.", "grade; year (school)", "我妹妹上三年级。", "Wǒ mèimei shàng sān niánjí.", "My younger sister is in third grade."],
  ["年轻", "niánqīng", "adj.", "young", "她还很年轻。", "Tā hái hěn niánqīng.", "She is still very young."],
  ["牛", "niú", "n./adj.", "cow; ox", "田里有一头牛。", "Tián lǐ yǒu yì tóu niú.", "There is a cow in the field."],
  ["努力", "nǔlì", "v./adj.", "to work hard; diligent", "他学习很努力。", "Tā xuéxí hěn nǔlì.", "He studies very hard."],
  ["女人", "nǚrén", "n.", "woman", "那个女人是医生。", "Nàge nǚrén shì yīshēng.", "That woman is a doctor."],
  ["女生", "nǚshēng", "n.", "female student; girl", "我们班的女生很多。", "Wǒmen bān de nǚshēng hěn duō.", "There are many girls in our class."],
  ["爬", "pá", "v.", "to climb; to crawl", "我们一起爬山吧。", "Wǒmen yìqǐ pá shān ba.", "Let's climb the mountain together."],
  ["怕", "pà", "v./adv.", "to fear; to be afraid", "我怕狗。", "Wǒ pà gǒu.", "I am afraid of dogs."],
  ["拍照", "pāizhào", "v.", "to take photos", "我们在这里拍照吧。", "Wǒmen zài zhèlǐ pāizhào ba.", "Let's take photos here."],
  ["盘子", "pánzi", "n.", "plate; dish", "桌子上有一个盘子。", "Zhuōzi shàng yǒu yí ge pánzi.", "There is a plate on the table."],
  ["胖", "pàng", "adj.", "fat", "这只猫有点胖。", "Zhè zhī māo yǒudiǎn pàng.", "This cat is a bit fat."],
  ["啤酒", "píjiǔ", "n.", "beer", "他喜欢喝啤酒。", "Tā xǐhuan hē píjiǔ.", "He likes to drink beer."],
  ["平时", "píngshí", "n.", "usually; ordinary times", "我平时六点起床。", "Wǒ píngshí liù diǎn qǐchuáng.", "I usually get up at six."],
  ["瓶子", "píngzi", "n.", "bottle", "这个瓶子是空的。", "Zhège píngzi shì kōng de.", "This bottle is empty."],
  ["骑", "qí", "v.", "to ride", "他骑自行车去学校。", "Tā qí zìxíngchē qù xuéxiào.", "He rides a bicycle to school."],
  ["奇怪", "qíguài", "adj.", "strange; odd", "这件事很奇怪。", "Zhè jiàn shì hěn qíguài.", "This matter is very strange."],
  ["其实", "qíshí", "adv.", "actually; in fact", "其实我也不知道。", "Qíshí wǒ yě bù zhīdào.", "Actually, I don't know either."],
  ["其他", "qítā", "pron.", "other; else", "还有其他问题吗？", "Hái yǒu qítā wèntí ma?", "Are there any other questions?"],
  ["起", "qǐ", "v./mw.", "to rise; to get up", "我每天七点起。", "Wǒ měitiān qī diǎn qǐ.", "I get up at seven every day."],
  ["起飞", "qǐfēi", "v.", "to take off", "飞机马上就要起飞了。", "Fēijī mǎshàng jiù yào qǐfēi le.", "The plane is about to take off."],
  ["汽车", "qìchē", "n.", "car; automobile", "他买了一辆新汽车。", "Tā mǎi le yí liàng xīn qìchē.", "He bought a new car."],
  ["铅笔", "qiānbǐ", "n.", "pencil", "我用铅笔写字。", "Wǒ yòng qiānbǐ xiě zì.", "I write with a pencil."],
  ["前年", "qiánnián", "n.", "year before last", "我前年来过这里。", "Wǒ qiánnián lái guò zhèlǐ.", "I came here the year before last."],
  ["前天", "qiántiān", "n.", "day before yesterday", "他前天回来了。", "Tā qiántiān huílái le.", "He came back the day before yesterday."],
  ["清楚", "qīngchu", "adj./v.", "clear; to be clear about", "请说清楚一点。", "Qǐng shuō qīngchu yìdiǎn.", "Please speak a little more clearly."],
  ["请假", "qǐngjià", "v.", "to ask for leave", "我明天想请假。", "Wǒ míngtiān xiǎng qǐngjià.", "I want to ask for leave tomorrow."],
  ["请客", "qǐngkè", "v.", "to treat (a guest)", "今天我请客。", "Jīntiān wǒ qǐngkè.", "Today it's my treat."],
  ["秋天", "qiūtiān", "n.", "autumn; fall", "秋天的天气很好。", "Qiūtiān de tiānqì hěn hǎo.", "The weather in autumn is nice."],
  ["球场", "qiúchǎng", "n.", "ball court; field", "他们在球场上打球。", "Tāmen zài qiúchǎng shàng dǎ qiú.", "They are playing ball on the court."],
  ["裙子", "qúnzi", "n.", "skirt", "她穿了一条红裙子。", "Tā chuān le yì tiáo hóng qúnzi.", "She wore a red skirt."],
  ["然后", "ránhòu", "conj.", "then; afterward", "先吃饭，然后看电影。", "Xiān chīfàn, ránhòu kàn diànyǐng.", "First eat, then watch a movie."],
  ["热情", "rèqíng", "adj.", "warm; enthusiastic", "这里的人很热情。", "Zhèlǐ de rén hěn rèqíng.", "The people here are very warm."],
  ["认得", "rènde", "v.", "to recognize", "我认得这个字。", "Wǒ rènde zhège zì.", "I recognize this character."],
  ["认为", "rènwéi", "v.", "to think; to believe", "我认为他是对的。", "Wǒ rènwéi tā shì duì de.", "I think he is right."],
  ["认真", "rènzhēn", "adj.", "serious; conscientious", "她工作很认真。", "Tā gōngzuò hěn rènzhēn.", "She works very conscientiously."],
  ["容易", "róngyì", "adj.", "easy", "这道题很容易。", "Zhè dào tí hěn róngyì.", "This problem is very easy."],
  ["如果", "rúguǒ", "conj.", "if", "如果下雨我就不去。", "Rúguǒ xiàyǔ wǒ jiù bú qù.", "If it rains I won't go."],
  ["伞", "sǎn", "n.", "umbrella", "别忘了带伞。", "Bié wàng le dài sǎn.", "Don't forget to bring an umbrella."],
  ["扫", "sǎo", "v.", "to sweep", "她在扫地。", "Tā zài sǎo dì.", "She is sweeping the floor."],
  ["沙发", "shāfā", "n.", "sofa; couch", "他坐在沙发上。", "Tā zuò zài shāfā shàng.", "He is sitting on the sofa."],
  ["山", "shān", "n.", "mountain; hill", "那座山很高。", "Nà zuò shān hěn gāo.", "That mountain is very high."],
  ["上衣", "shàngyī", "n.", "upper garment; jacket", "这件上衣很好看。", "Zhè jiàn shàngyī hěn hǎokàn.", "This jacket looks nice."],
  ["勺子", "sháozi", "n.", "spoon", "请给我一把勺子。", "Qǐng gěi wǒ yì bǎ sháozi.", "Please give me a spoon."],
  ["身边", "shēnbiān", "n.", "at one's side", "她一直在我身边。", "Tā yìzhí zài wǒ shēnbiān.", "She has always been by my side."],
  ["身高", "shēngāo", "n.", "height (of a person)", "他的身高是一米八。", "Tā de shēngāo shì yì mǐ bā.", "His height is one meter eighty."],
  ["声", "shēng", "n./mw.", "sound; voice", "我听到一声响。", "Wǒ tīngdào yì shēng xiǎng.", "I heard a sound."],
  ["生活", "shēnghuó", "n./v.", "life; to live", "他的生活很简单。", "Tā de shēnghuó hěn jiǎndān.", "His life is very simple."],
  ["生气", "shēngqì", "v.", "to get angry", "他生气了。", "Tā shēngqì le.", "He got angry."],
  ["声音", "shēngyīn", "n.", "sound; voice", "她的声音很好听。", "Tā de shēngyīn hěn hǎotīng.", "Her voice is very pleasant."],
  ["市", "shì", "n.", "city; market", "这是一座大城市。", "Zhè shì yí zuò dà chéngshì.", "This is a big city."],
  ["试", "shì", "v.", "to try; to test", "你试一下这件衣服。", "Nǐ shì yíxià zhè jiàn yīfu.", "Try on this piece of clothing."],
  ["室", "shì", "n.", "room", "这是办公室。", "Zhè shì bàngōngshì.", "This is the office."],
  ["世界", "shìjiè", "n.", "world", "世界很大。", "Shìjiè hěn dà.", "The world is very big."],
  ["收", "shōu", "v.", "to receive; to collect", "我收到了你的信。", "Wǒ shōudào le nǐ de xìn.", "I received your letter."],
  ["收到", "shōudào", "v.", "to receive", "我收到了一个包裹。", "Wǒ shōudào le yí ge bāoguǒ.", "I received a package."],
  ["受", "shòu", "v.", "to receive; to suffer", "他受了伤。", "Tā shòu le shāng.", "He got injured."],
  ["瘦", "shòu", "adj.", "thin; lean", "她比以前瘦了。", "Tā bǐ yǐqián shòu le.", "She is thinner than before."],
  ["受到", "shòudào", "v.", "to receive; to be subjected to", "他受到了表扬。", "Tā shòudào le biǎoyáng.", "He received praise."],
  ["叔叔", "shūshu", "n.", "uncle (father's younger brother)", "我的叔叔很高。", "Wǒ de shūshu hěn gāo.", "My uncle is very tall."],
  ["树", "shù", "n.", "tree", "门前有一棵大树。", "Mén qián yǒu yì kē dà shù.", "There is a big tree in front of the door."],
  ["数学", "shùxué", "n.", "mathematics", "我喜欢数学。", "Wǒ xǐhuan shùxué.", "I like mathematics."],
  ["刷", "shuā", "v.", "to brush; to scrub", "我每天早上刷牙。", "Wǒ měitiān zǎoshang shuā yá.", "I brush my teeth every morning."],
  ["双", "shuāng", "mw.", "pair (measure word)", "我买了一双鞋。", "Wǒ mǎi le yì shuāng xié.", "I bought a pair of shoes."],
  ["水平", "shuǐpíng", "n.", "level; standard", "他的中文水平很高。", "Tā de Zhōngwén shuǐpíng hěn gāo.", "His Chinese level is very high."],
  ["司机", "sījī", "n.", "driver", "司机开车很小心。", "Sījī kāichē hěn xiǎoxīn.", "The driver drives very carefully."],
  ["四季", "sìjì", "n.", "four seasons", "这里四季都很美。", "Zhèlǐ sìjì dōu hěn měi.", "It is beautiful here in all four seasons."],
  ["太阳", "tàiyáng", "n.", "sun", "今天太阳很大。", "Jīntiān tàiyáng hěn dà.", "The sun is strong today."],
  ["糖", "táng", "n.", "sugar; candy", "孩子喜欢吃糖。", "Háizi xǐhuan chī táng.", "Children like to eat candy."],
  ["特别", "tèbié", "adj./adv.", "special; especially", "今天天气特别好。", "Jīntiān tiānqì tèbié hǎo.", "The weather is especially nice today."],
  ["提高", "tígāo", "v.", "to raise; to improve", "我想提高我的成绩。", "Wǒ xiǎng tígāo wǒ de chéngjì.", "I want to improve my grades."],
  ["体育", "tǐyù", "n.", "physical education; sports", "我喜欢上体育课。", "Wǒ xǐhuan shàng tǐyù kè.", "I like attending PE class."],
  ["体育馆", "tǐyùguǎn", "n.", "gymnasium", "我们去体育馆打球。", "Wǒmen qù tǐyùguǎn dǎ qiú.", "We go to the gym to play ball."],
  ["甜", "tián", "adj.", "sweet", "这个西瓜很甜。", "Zhège xīguā hěn tián.", "This watermelon is very sweet."],
  ["跳", "tiào", "v.", "to jump; to dance", "她跳得很好。", "Tā tiào de hěn hǎo.", "She dances very well."],
  ["听说", "tīngshuō", "v.", "to hear; it is said", "我听说他要来。", "Wǒ tīngshuō tā yào lái.", "I heard he is coming."],
  ["挺", "tǐng", "adv./v.", "quite; rather", "这个菜挺好吃。", "Zhège cài tǐng hǎochī.", "This dish is quite tasty."],
  ["同事", "tóngshì", "n.", "colleague", "他是我的同事。", "Tā shì wǒ de tóngshì.", "He is my colleague."],
  ["同意", "tóngyì", "v.", "to agree", "我同意你的看法。", "Wǒ tóngyì nǐ de kànfǎ.", "I agree with your view."],
  ["头发", "tóufa", "n.", "hair", "她的头发很长。", "Tā de tóufa hěn cháng.", "Her hair is very long."],
  ["突然", "tūrán", "adj.", "sudden; suddenly", "天突然下雨了。", "Tiān tūrán xià yǔ le.", "It suddenly started to rain."],
  ["图书馆", "túshūguǎn", "n.", "library", "我在图书馆看书。", "Wǒ zài túshūguǎn kàn shū.", "I read books in the library."],
  ["腿", "tuǐ", "n.", "leg", "我的腿很疼。", "Wǒ de tuǐ hěn téng.", "My legs hurt a lot."],
  ["外地", "wàidì", "n.", "other places; out of town", "他从外地来。", "Tā cóng wàidì lái.", "He comes from another place."],
  ["外卖", "wàimài", "v./n.", "takeout; food delivery", "今天我们点外卖吧。", "Jīntiān wǒmen diǎn wàimài ba.", "Let's order takeout today."],
  ["外语", "wàiyǔ", "n.", "foreign language", "她会三门外语。", "Tā huì sān mén wàiyǔ.", "She knows three foreign languages."],
  ["完成", "wánchéng", "v.", "to complete; to finish", "我完成了作业。", "Wǒ wánchéng le zuòyè.", "I finished my homework."],
  ["碗", "wǎn", "n.", "bowl", "桌子上有一个碗。", "Zhuōzi shàng yǒu yí ge wǎn.", "There is a bowl on the table."],
  ["晚点", "wǎndiǎn", "v.", "to be delayed; late", "火车晚点了。", "Huǒchē wǎndiǎn le.", "The train is delayed."],
  ["晚会", "wǎnhuì", "n.", "evening party", "今晚有一个晚会。", "Jīnwǎn yǒu yí ge wǎnhuì.", "There is a party tonight."],
  ["网球", "wǎngqiú", "n.", "tennis", "我喜欢打网球。", "Wǒ xǐhuan dǎ wǎngqiú.", "I like playing tennis."],
  ["网站", "wǎngzhàn", "n.", "website", "这个网站很有用。", "Zhège wǎngzhàn hěn yǒuyòng.", "This website is very useful."],
  ["忘记", "wàngjì", "v.", "to forget", "我忘记带钥匙了。", "Wǒ wàngjì dài yàoshi le.", "I forgot to bring my keys."],
  ["为", "wèi", "prep.", "for; for the sake of", "我为你高兴。", "Wǒ wèi nǐ gāoxìng.", "I am happy for you."],
  ["为了", "wèile", "prep.", "in order to; for", "为了健康，他每天运动。", "Wèile jiànkāng, tā měitiān yùndòng.", "For his health, he exercises every day."],
  ["卫生间", "wèishēngjiān", "n.", "bathroom; toilet", "卫生间在哪里？", "Wèishēngjiān zài nǎlǐ?", "Where is the bathroom?"],
  ["文化", "wénhuà", "n.", "culture", "我喜欢中国文化。", "Wǒ xǐhuan Zhōngguó wénhuà.", "I like Chinese culture."],
  ["屋子", "wūzi", "n.", "room", "这间屋子很干净。", "Zhè jiān wūzi hěn gānjìng.", "This room is very clean."],
  ["西", "xī", "n.", "west", "太阳从西边落下。", "Tàiyáng cóng xībian luòxià.", "The sun sets in the west."],
  ["西北", "xīběi", "n.", "northwest", "他住在城市的西北。", "Tā zhù zài chéngshì de xīběi.", "He lives in the northwest of the city."],
  ["西方", "xīfāng", "n.", "the West", "他对西方文化很感兴趣。", "Tā duì xīfāng wénhuà hěn gǎn xìngqù.", "He is very interested in Western culture."],
  ["西瓜", "xīguā", "n.", "watermelon", "夏天我爱吃西瓜。", "Xiàtiān wǒ ài chī xīguā.", "I love eating watermelon in summer."],
  ["西南", "xīnán", "n.", "southwest", "她家在城市的西南。", "Tā jiā zài chéngshì de xīnán.", "Her home is in the southwest of the city."],
  ["习惯", "xíguàn", "v./n.", "habit; to be used to", "我习惯早起。", "Wǒ xíguàn zǎo qǐ.", "I am used to getting up early."],
  ["喜爱", "xǐ'ài", "v.", "to like; to love", "孩子们喜爱这本书。", "Háizimen xǐ'ài zhè běn shū.", "The children love this book."],
  ["洗衣机", "xǐyījī", "n.", "washing machine", "洗衣机坏了。", "Xǐyījī huài le.", "The washing machine is broken."],
  ["洗澡", "xǐzǎo", "v.", "to bathe; take a shower", "我每天晚上洗澡。", "Wǒ měitiān wǎnshang xǐzǎo.", "I take a shower every night."],
  ["夏天", "xiàtiān", "n.", "summer", "夏天天气很热。", "Xiàtiān tiānqì hěn rè.", "The weather is hot in summer."],
  ["先", "xiān", "adv.", "first; in advance", "你先走吧。", "Nǐ xiān zǒu ba.", "You go first."],
  ["香蕉", "xiāngjiāo", "n.", "banana", "我早上吃了一根香蕉。", "Wǒ zǎoshang chī le yì gēn xiāngjiāo.", "I ate a banana in the morning."],
  ["相信", "xiāngxìn", "v.", "to believe", "我相信你能做到。", "Wǒ xiāngxìn nǐ néng zuòdào.", "I believe you can do it."],
  ["箱子", "xiāngzi", "n.", "box; suitcase", "这个箱子很重。", "Zhège xiāngzi hěn zhòng.", "This suitcase is very heavy."],
  ["向", "xiàng", "v./prep.", "toward; to face", "请向前走。", "Qǐng xiàng qián zǒu.", "Please walk forward."],
  ["像", "xiàng", "v./adv./n.", "to resemble; like", "他长得像他爸爸。", "Tā zhǎng de xiàng tā bàba.", "He looks like his father."],
  ["相机", "xiàngjī", "n.", "camera", "我带了相机去旅行。", "Wǒ dài le xiàngjī qù lǚxíng.", "I took a camera on the trip."],
  ["小区", "xiǎoqū", "n.", "residential community", "我们小区很安静。", "Wǒmen xiǎoqū hěn ānjìng.", "Our neighborhood is very quiet."],
  ["小心", "xiǎoxīn", "v./adj.", "careful; be careful", "过马路要小心。", "Guò mǎlù yào xiǎoxīn.", "Be careful crossing the road."],
  ["校园", "xiàoyuán", "n.", "campus", "我们的校园很大。", "Wǒmen de xiàoyuán hěn dà.", "Our campus is very big."],
  ["校长", "xiàozhǎng", "n.", "principal; headmaster", "校长在开会。", "Xiàozhǎng zài kāihuì.", "The principal is in a meeting."],
  ["鞋", "xié", "n.", "shoes", "这双鞋很漂亮。", "Zhè shuāng xié hěn piàoliang.", "These shoes are very pretty."],
  ["心里", "xīnlǐ", "n.", "in the heart; mind", "我心里很高兴。", "Wǒ xīnlǐ hěn gāoxìng.", "I feel very happy inside."],
  ["新年", "xīnnián", "n.", "New Year", "新年快乐！", "Xīnnián kuàilè!", "Happy New Year!"],
  ["新闻", "xīnwén", "n.", "news", "我每天看新闻。", "Wǒ měitiān kàn xīnwén.", "I watch the news every day."],
  ["新鲜", "xīnxiān", "adj.", "fresh", "这些蔬菜很新鲜。", "Zhèxiē shūcài hěn xīnxiān.", "These vegetables are very fresh."],
  ["信", "xìn", "v./n.", "letter; to believe", "我给妈妈写了一封信。", "Wǒ gěi māma xiě le yì fēng xìn.", "I wrote a letter to my mom."],
  ["信用卡", "xìnyòngkǎ", "n.", "credit card", "我用信用卡付钱。", "Wǒ yòng xìnyòngkǎ fù qián.", "I pay with a credit card."],
  ["行", "xíng", "v./adj.", "to be okay; alright", "这样做行吗？", "Zhèyàng zuò xíng ma?", "Is it okay to do it this way?"],
  ["行李", "xíngli", "n.", "luggage", "我的行李很多。", "Wǒ de xíngli hěn duō.", "I have a lot of luggage."],
  ["兴趣", "xìngqù", "n.", "interest", "我对音乐很有兴趣。", "Wǒ duì yīnyuè hěn yǒu xìngqù.", "I am very interested in music."],
  ["休假", "xiūjià", "v.", "to take a vacation", "他下周休假。", "Tā xiàzhōu xiūjià.", "He is taking a vacation next week."],
  ["需要", "xūyào", "v./n.", "to need; need", "我需要你的帮助。", "Wǒ xūyào nǐ de bāngzhù.", "I need your help."],
  ["选", "xuǎn", "v.", "to choose; to select", "请选一个颜色。", "Qǐng xuǎn yí ge yánsè.", "Please choose a color."],
  ["选择", "xuǎnzé", "v.", "to choose; choice", "我选择了这份工作。", "Wǒ xuǎnzé le zhè fèn gōngzuò.", "I chose this job."],
  ["学期", "xuéqī", "n.", "semester; term", "这个学期很忙。", "Zhège xuéqī hěn máng.", "This semester is very busy."],
  ["牙", "yá", "n.", "tooth", "我的牙很疼。", "Wǒ de yá hěn téng.", "My tooth hurts a lot."],
  ["牙刷", "yáshuā", "n.", "toothbrush", "我买了一把新牙刷。", "Wǒ mǎi le yì bǎ xīn yáshuā.", "I bought a new toothbrush."],
  ["羊", "yáng", "n.", "sheep; goat", "山上有很多羊。", "Shān shàng yǒu hěn duō yáng.", "There are many sheep on the mountain."],
  ["养", "yǎng", "v.", "to raise; to keep", "她养了一只猫。", "Tā yǎng le yì zhī māo.", "She keeps a cat."],
  ["要求", "yāoqiú", "v./n.", "to require; requirement", "老师对我们要求很高。", "Lǎoshī duì wǒmen yāoqiú hěn gāo.", "The teacher has high requirements for us."],
  ["页", "yè", "mw.", "page", "这本书有三百页。", "Zhè běn shū yǒu sānbǎi yè.", "This book has three hundred pages."],
  ["一定", "yídìng", "adj./adv.", "certain; surely", "我明天一定来。", "Wǒ míngtiān yídìng lái.", "I will definitely come tomorrow."],
  ["一共", "yígòng", "adv.", "altogether; in total", "我们一共花了一百块。", "Wǒmen yígòng huā le yìbǎi kuài.", "We spent one hundred yuan in total."],
  ["一块儿", "yíkuàir", "n./adv.", "together", "我们一块儿吃饭吧。", "Wǒmen yíkuàir chīfàn ba.", "Let's eat together."],
  ["一样", "yíyàng", "adj.", "same; alike", "这两个杯子一样。", "Zhè liǎng gè bēizi yíyàng.", "These two cups are the same."],
  ["以后", "yǐhòu", "n.", "after; later", "下课以后我们去玩。", "Xiàkè yǐhòu wǒmen qù wán.", "We'll go play after class."],
  ["以前", "yǐqián", "n.", "before; previously", "以前我住在北京。", "Yǐqián wǒ zhù zài Běijīng.", "I lived in Beijing before."],
  ["以上", "yǐshàng", "n.", "above; more than", "十岁以上才能参加。", "Shí suì yǐshàng cái néng cānjiā.", "Only those over ten can join."],
  ["以外", "yǐwài", "n.", "besides; outside of", "除了他以外都来了。", "Chúle tā yǐwài dōu lái le.", "Everyone except him came."],
  ["以为", "yǐwéi", "v.", "think; assume (mistakenly)", "我以为你不来了。", "Wǒ yǐwéi nǐ bù lái le.", "I thought you weren't coming."],
  ["以下", "yǐxià", "n.", "below; less than", "六岁以下免费。", "Liù suì yǐxià miǎnfèi.", "Under six years old is free."],
  ["一般", "yìbān", "adj.", "ordinary; general", "这家饭店很一般。", "Zhè jiā fàndiàn hěn yìbān.", "This restaurant is just so-so."],
  ["一边", "yìbiān", "adv.", "at the same time", "他一边走一边唱。", "Tā yìbiān zǒu yìbiān chàng.", "He walks and sings at the same time."],
  ["一直", "yìzhí", "adv.", "continuously; always", "他一直在等你。", "Tā yìzhí zài děng nǐ.", "He has been waiting for you."],
  ["音乐", "yīnyuè", "n.", "music", "我喜欢听音乐。", "Wǒ xǐhuan tīng yīnyuè.", "I like listening to music."],
  ["银行", "yínháng", "n.", "bank", "我去银行取钱。", "Wǒ qù yínháng qǔ qián.", "I'm going to the bank to withdraw money."],
  ["银行卡", "yínhángkǎ", "n.", "bank card", "请输入银行卡密码。", "Qǐng shūrù yínhángkǎ mìmǎ.", "Please enter your bank card password."],
  ["饮料", "yǐnliào", "n.", "drink; beverage", "你想喝什么饮料？", "Nǐ xiǎng hē shénme yǐnliào?", "What drink would you like?"],
  ["应该", "yīnggāi", "v.", "should; ought to", "你应该早点睡觉。", "Nǐ yīnggāi zǎodiǎn shuìjiào.", "You should sleep earlier."],
  ["影响", "yǐngxiǎng", "v./n.", "influence; affect", "天气影响了我的心情。", "Tiānqì yǐngxiǎng le wǒ de xīnqíng.", "The weather affected my mood."],
  ["用", "yòng", "v.", "use", "我可以用一下你的笔吗？", "Wǒ kěyǐ yòng yíxià nǐ de bǐ ma?", "May I use your pen?"],
  ["邮件", "yóujiàn", "n.", "mail; email", "我给你发了一封邮件。", "Wǒ gěi nǐ fā le yì fēng yóujiàn.", "I sent you an email."],
  ["游客", "yóukè", "n.", "tourist", "这里有很多游客。", "Zhèlǐ yǒu hěn duō yóukè.", "There are many tourists here."],
  ["游戏", "yóuxì", "n.", "game", "孩子们在玩游戏。", "Háizimen zài wán yóuxì.", "The children are playing games."],
  ["邮箱", "yóuxiāng", "n.", "mailbox; email address", "请告诉我你的邮箱。", "Qǐng gàosu wǒ nǐ de yóuxiāng.", "Please tell me your email address."],
  ["有关", "yǒuguān", "v./prep.", "be related to; concerning", "这件事和你有关。", "Zhè jiàn shì hé nǐ yǒuguān.", "This matter is related to you."],
  ["有名", "yǒumíng", "adj.", "famous", "他是个有名的画家。", "Tā shì gè yǒumíng de huàjiā.", "He is a famous painter."],
  ["有用", "yǒuyòng", "adj.", "useful", "这本书很有用。", "Zhè běn shū hěn yǒuyòng.", "This book is very useful."],
  ["又", "yòu", "adv.", "again; also", "他又迟到了。", "Tā yòu chídào le.", "He was late again."],
  ["羽毛球", "yǔmáoqiú", "n.", "badminton", "我们去打羽毛球吧。", "Wǒmen qù dǎ yǔmáoqiú ba.", "Let's go play badminton."],
  ["语言", "yǔyán", "n.", "language", "汉语是很美的语言。", "Hànyǔ shì hěn měi de yǔyán.", "Chinese is a beautiful language."],
  ["雨衣", "yǔyī", "n.", "raincoat", "下雨了，穿上雨衣。", "Xiàyǔ le, chuān shàng yǔyī.", "It's raining, put on your raincoat."],
  ["遇到", "yùdào", "v.", "encounter; run into", "我在路上遇到了老师。", "Wǒ zài lùshang yùdào le lǎoshī.", "I ran into my teacher on the road."],
  ["遇见", "yùjiàn", "v.", "meet; come across", "我昨天遇见了他。", "Wǒ zuótiān yùjiàn le tā.", "I came across him yesterday."],
  ["园", "yuán", "n.", "garden; park", "公园里有一个花园。", "Gōngyuán lǐ yǒu yí gè huāyuán.", "There is a garden in the park."],
  ["员", "yuán", "part.", "member; -er (suffix)", "他是公司的一员。", "Tā shì gōngsī de yì yuán.", "He is a member of the company."],
  ["愿意", "yuànyì", "v.", "be willing to", "我愿意帮助你。", "Wǒ yuànyì bāngzhù nǐ.", "I am willing to help you."],
  ["越", "yuè", "adv.", "the more...", "雨越下越大。", "Yǔ yuè xià yuè dà.", "The rain gets heavier and heavier."],
  ["月亮", "yuèliang", "n.", "moon", "今晚的月亮很圆。", "Jīnwǎn de yuèliang hěn yuán.", "Tonight's moon is very round."],
  ["运动会", "yùndònghuì", "n.", "sports meet", "学校下周开运动会。", "Xuéxiào xià zhōu kāi yùndònghuì.", "The school holds a sports meet next week."],
  ["运动员", "yùndòngyuán", "n.", "athlete", "他是一名运动员。", "Tā shì yì míng yùndòngyuán.", "He is an athlete."],
  ["咱们", "zánmen", "pron.", "we (inclusive)", "咱们一起走吧。", "Zánmen yìqǐ zǒu ba.", "Let's go together."],
  ["脏", "zāng", "adj.", "dirty", "你的手很脏。", "Nǐ de shǒu hěn zāng.", "Your hands are dirty."],
  ["怎么办", "zěnme bàn", "phr.", "what to do", "我丢了钱包，怎么办？", "Wǒ diū le qiánbāo, zěnme bàn?", "I lost my wallet, what should I do?"],
  ["怎样", "zěnyàng", "pron.", "how; in what way", "这件衣服怎样？", "Zhè jiàn yīfu zěnyàng?", "How is this piece of clothing?"],
  ["站", "zhàn", "v.", "stand", "请大家站起来。", "Qǐng dàjiā zhàn qǐlái.", "Everyone please stand up."],
  ["张", "zhāng", "v./mw.", "open; (measure word)", "给我一张纸。", "Gěi wǒ yì zhāng zhǐ.", "Give me a sheet of paper."],
  ["长", "zhǎng", "v./part.", "grow; chief", "小树长高了。", "Xiǎo shù zhǎng gāo le.", "The little tree has grown tall."],
  ["着急", "zháojí", "adj.", "anxious; worried", "别着急，慢慢来。", "Bié zháojí, mànman lái.", "Don't worry, take your time."],
  ["照", "zhào", "v.", "shine; take (photo)", "阳光照进房间。", "Yángguāng zhào jìn fángjiān.", "Sunlight shines into the room."],
  ["照顾", "zhàogù", "v.", "take care of", "她照顾生病的妈妈。", "Tā zhàogù shēngbìng de māma.", "She takes care of her sick mother."],
  ["照片", "zhàopiàn", "n.", "photograph", "这张照片很漂亮。", "Zhè zhāng zhàopiàn hěn piàoliang.", "This photo is very pretty."],
  ["照相", "zhàoxiàng", "v.", "take a photo", "我们一起照相吧。", "Wǒmen yìqǐ zhàoxiàng ba.", "Let's take a photo together."],
  ["直到", "zhídào", "v.", "until; up to", "我直到现在才明白。", "Wǒ zhídào xiànzài cái míngbai.", "I didn't understand until now."],
  ["只", "zhǐ", "adv.", "only; just", "我只想要一个。", "Wǒ zhǐ xiǎng yào yí gè.", "I only want one."],
  ["纸", "zhǐ", "n.", "paper", "桌上有一张纸。", "Zhuō shàng yǒu yì zhāng zhǐ.", "There is a sheet of paper on the desk."],
  ["只能", "zhǐ néng", "adv.", "can only", "我们只能等明天了。", "Wǒmen zhǐ néng děng míngtiān le.", "We can only wait until tomorrow."],
  ["只是", "zhǐshì", "adv./conj.", "merely; but", "我只是开个玩笑。", "Wǒ zhǐshì kāi gè wánxiào.", "I was just making a joke."],
  ["只要", "zhǐyào", "conj.", "as long as", "只要努力就会成功。", "Zhǐyào nǔlì jiù huì chénggōng.", "As long as you work hard, you will succeed."],
  ["只有", "zhǐyǒu", "conj.", "only if; only", "只有他知道答案。", "Zhǐyǒu tā zhīdào dáàn.", "Only he knows the answer."],
  ["中", "zhōng", "n.", "middle; center", "他在人群中。", "Tā zài rénqún zhōng.", "He is in the crowd."],
  ["中间", "zhōngjiān", "n.", "middle; between", "他坐在中间。", "Tā zuò zài zhōngjiān.", "He sits in the middle."],
  ["终于", "zhōngyú", "adv.", "finally; at last", "我终于到家了。", "Wǒ zhōngyú dào jiā le.", "I finally got home."],
  ["种", "zhǒng", "mw.", "kind; type", "这种花很香。", "Zhè zhǒng huā hěn xiāng.", "This kind of flower is fragrant."],
  ["重要", "zhòngyào", "adj.", "important", "这是一件重要的事。", "Zhè shì yí jiàn zhòngyào de shì.", "This is an important matter."],
  ["周末", "zhōumò", "n.", "weekend", "周末我们去爬山。", "Zhōumò wǒmen qù páshān.", "We'll go hiking on the weekend."],
  ["主要", "zhǔyào", "adj.", "main; primary", "这是主要的原因。", "Zhè shì zhǔyào de yuányīn.", "This is the main reason."],
  ["注意", "zhùyì", "v.", "pay attention to", "过马路要注意安全。", "Guò mǎlù yào zhùyì ānquán.", "Pay attention to safety when crossing the road."],
  ["住院", "zhùyuàn", "v.", "be hospitalized", "爷爷住院了。", "Yéye zhùyuàn le.", "Grandpa was hospitalized."],
  ["字典", "zìdiǎn", "n.", "dictionary", "我用字典查生词。", "Wǒ yòng zìdiǎn chá shēngcí.", "I use a dictionary to look up new words."],
  ["自行车", "zìxíngchē", "n.", "bicycle", "我骑自行车上学。", "Wǒ qí zìxíngchē shàngxué.", "I ride a bicycle to school."],
  ["子", "zi", "part.", "(noun suffix)", "桌子上有一本书。", "Zhuōzi shàng yǒu yì běn shū.", "There is a book on the table."],
  ["总", "zǒng", "adv.", "always; general", "他总是迟到。", "Tā zǒngshì chídào.", "He is always late."],
  ["总是", "zǒngshì", "adv.", "always", "她总是面带微笑。", "Tā zǒngshì miàn dài wéixiào.", "She always wears a smile."],
  ["嘴", "zuǐ", "n.", "mouth", "请张开你的嘴。", "Qǐng zhāngkāi nǐ de zuǐ.", "Please open your mouth."],
  ["最好", "zuìhǎo", "adv.", "had better; best", "你最好早点回家。", "Nǐ zuìhǎo zǎodiǎn huíjiā.", "You had better go home early."],
  ["最后", "zuìhòu", "n.", "last; finally", "最后他赢了比赛。", "Zuìhòu tā yíng le bǐsài.", "In the end he won the match."],
  ["最近", "zuìjìn", "n.", "recently; lately", "你最近怎么样？", "Nǐ zuìjìn zěnmeyàng?", "How have you been recently?"],
  ["做客", "zuòkè", "v.", "be a guest", "今天我去朋友家做客。", "Jīntiān wǒ qù péngyou jiā zuòkè.", "Today I'm visiting a friend as a guest."],
  ["作业", "zuòyè", "n.", "homework", "我在写作业。", "Wǒ zài xiě zuòyè.", "I am doing my homework."],
];
