// HSK 4 (Band 4) vocabulary, 1000 words from the official 词汇大纲 (HSK 考试大纲, 2025).
// Hanzi, pinyin, and part-of-speech are taken directly from the syllabus PDF.
// English glosses and example sentences are study aids authored for this course.
// Each entry: [hanzi, pinyin, pos, english, example_hanzi, example_pinyin, example_english]
window.BAND4_WORDS = [
  ["啊","ā","interj.","ah / oh (exclamation)","啊，你来了！","Ā, nǐ lái le!","Oh, you're here!"],
  ["爱情","àiqíng","n.","love; romance","他们的爱情很美。","Tāmen de àiqíng hěn měi.","Their love is beautiful."],
  ["爱心","àixīn","n.","compassion; loving heart","她很有爱心。","Tā hěn yǒu àixīn.","She is very kind-hearted."],
  ["安检","ānjiǎn","v.","security check","请先做安检。","Qǐng xiān zuò ānjiǎn.","Please go through security first."],
  ["安排","ānpái","v.","to arrange; arrangement","我安排了会议。","Wǒ ānpái le huìyì.","I arranged the meeting."],
  ["按","àn","v.","to press; according to","请按这个按钮。","Qǐng àn zhège ànniǔ.","Please press this button."],
  ["按时","ànshí","adv.","on time","他按时到了。","Tā ànshí dào le.","He arrived on time."],
  ["按照","ànzhào","prep.","according to","按照计划做。","Ànzhào jìhuà zuò.","Do it according to the plan."],
  ["白酒","báijiǔ","n.","Chinese liquor; baijiu","他不喝白酒。","Tā bù hē báijiǔ.","He doesn't drink baijiu."],
  ["办公","bàngōng","v.","to work (in an office)","我在家办公。","Wǒ zài jiā bàngōng.","I work from home."],
  ["办理","bànlǐ","v.","to handle; to process","我去办理签证。","Wǒ qù bànlǐ qiānzhèng.","I'm going to process my visa."],
  ["办事","bànshì","v.","to handle affairs","他在外面办事。","Tā zài wàimiàn bànshì.","He is out running errands."],
  ["棒","bàng","adj.","great; awesome","你真棒！","Nǐ zhēn bàng!","You're awesome!"],
  ["保护","bǎohù","v.","to protect","我们要保护环境。","Wǒmen yào bǎohù huánjìng.","We must protect the environment."],
  ["保证","bǎozhèng","v.","to guarantee; guarantee","我保证按时到。","Wǒ bǎozhèng ànshí dào.","I guarantee I'll arrive on time."],
  ["抱","bào","v.","to hold; to hug","妈妈抱着孩子。","Māma bào zhe háizi.","Mom is holding the child."],
  ["报考","bàokǎo","v.","to register for an exam","我想报考大学。","Wǒ xiǎng bàokǎo dàxué.","I want to apply for university."],
  ["报名","bàomíng","v.","to sign up; to register","请来这里报名。","Qǐng lái zhèlǐ bàomíng.","Please come here to sign up."],
  ["抱歉","bàoqiàn","adj.","sorry; apologetic","很抱歉，我迟到了。","Hěn bàoqiàn, wǒ chídào le.","I'm sorry, I'm late."],
  ["背","bēi","v.","to carry on the back","他背着书包。","Tā bēi zhe shūbāo.","He is carrying a backpack."],
  ["背包","bēibāo","n.","backpack","我的背包很重。","Wǒ de bēibāo hěn zhòng.","My backpack is heavy."],
  ["北部","běibù","n.","northern part","中国北部下雪了。","Zhōngguó běibù xià xuě le.","It's snowing in northern China."],
  ["倍","bèi","m.w.","times (fold)","今年是去年的两倍。","Jīnnián shì qùnián de liǎng bèi.","This year is twice last year."],
  ["本科","běnkē","n.","undergraduate program","她在读本科。","Tā zài dú běnkē.","She is studying undergraduate."],
  ["本来","běnlái","adj.","originally; original","我本来想去。","Wǒ běnlái xiǎng qù.","I originally wanted to go."],
  ["笨","bèn","adj.","stupid; clumsy","我太笨了。","Wǒ tài bèn le.","I'm so stupid."],
  ["鼻子","bízi","n.","nose","他的鼻子很大。","Tā de bízi hěn dà.","His nose is big."],
  ["笔试","bǐshì","v.","written exam","明天有笔试。","Míngtiān yǒu bǐshì.","There's a written exam tomorrow."],
  ["毕业","bìyè","v.","to graduate","我去年毕业了。","Wǒ qùnián bìyè le.","I graduated last year."],
  ["毕业生","bìyèshēng","n.","graduate (n.)","他是新毕业生。","Tā shì xīn bìyèshēng.","He is a new graduate."],
  ["便于","biànyú","v.","convenient for; easy to","便于学习。","Biànyú xuéxí.","Easy to study."],
  ["标准","biāozhǔn","n.","standard","这是行业标准。","Zhè shì hángyè biāozhǔn.","This is the industry standard."],
  ["表","biǎo","n.","watch; form; table","我有一块新表。","Wǒ yǒu yí kuài xīn biǎo.","I have a new watch."],
  ["表格","biǎogé","n.","form; table","请填这张表格。","Qǐng tián zhè zhāng biǎogé.","Please fill out this form."],
  ["表示","biǎoshì","v.","to express; to indicate","他表示同意。","Tā biǎoshì tóngyì.","He expressed agreement."],
  ["表现","biǎoxiàn","v.","to show; performance","他表现得很好。","Tā biǎoxiàn de hěn hǎo.","He performed very well."],
  ["表扬","biǎoyáng","v.","to praise; to commend","老师表扬了我。","Lǎoshī biǎoyáng le wǒ.","The teacher praised me."],
  ["饼干","bǐnggān","n.","biscuit; cracker","我喜欢吃饼干。","Wǒ xǐhuan chī bǐnggān.","I like eating biscuits."],
  ["并","bìng","v.","and; also; actually","他并不知道。","Tā bìng bù zhīdào.","He actually doesn't know."],
  ["并且","bìngqiě","conj.","and; moreover","便宜并且好。","Piányi bìngqiě hǎo.","Cheap and good."],
  ["播放","bōfàng","v.","to play (audio/video)","请播放音乐。","Qǐng bōfàng yīnyuè.","Please play the music."],
  ["博士","bóshì","n.","doctorate; PhD","他是博士。","Tā shì bóshì.","He is a PhD."],
  ["不必","búbì","adv.","need not; unnecessary","你不必担心。","Nǐ búbì dānxīn.","You don't need to worry."],
  ["不便","búbiàn","adj.","inconvenient","现在不便说话。","Xiànzài búbiàn shuōhuà.","It's not convenient to talk now."],
  ["不断","búduàn","v.","continuously; unceasing","雨不断地下。","Yǔ búduàn de xià.","The rain falls continuously."],
  ["不够","búgòu","v.","not enough","时间不够。","Shíjiān búgòu.","There isn't enough time."],
  ["不过","búguò","conj.","but; however","好，不过太贵。","Hǎo, búguò tài guì.","Good, but too expensive."],
  ["不论","búlùn","conj.","no matter (whether)","不论谁去都行。","Búlùn shéi qù dōu xíng.","No matter who goes is fine."],
  ["步","bù","n.","step; pace","走一步看一步。","Zǒu yí bù kàn yí bù.","Take it one step at a time."],
  ["部","bù","n.","part; ministry; copy","我读了一部小说。","Wǒ dú le yí bù xiǎoshuō.","I read a novel."],
  ["不得不","bùdébù","adv.","have to; must","我不得不走了。","Wǒ bùdébù zǒu le.","I have to go."],
  ["部分","bùfen","n.","part; portion","这部分很难。","Zhè bùfen hěn nán.","This part is difficult."],
  ["不管","bùguǎn","conj.","no matter (what)","不管多累，他都做。","Bùguǎn duō lèi, tā dōu zuò.","No matter how tired, he does it."],
  ["不光","bùguāng","adv.","not only","不光便宜，还好。","Bùguāng piányi, hái hǎo.","Not only cheap, also good."],
  ["不仅","bùjǐn","conj.","not only","不仅他来，我也来。","Bùjǐn tā lái, wǒ yě lái.","Not only him, I'll come too."],
  ["不满","bùmǎn","adj.","dissatisfied","他对结果不满。","Tā duì jiéguǒ bùmǎn.","He's unhappy with the result."],
  ["部门","bùmén","n.","department","她在销售部门。","Tā zài xiāoshòu bùmén.","She is in the sales department."],
  ["不如","bùrú","v.","not as good as","这不如那个。","Zhè bùrú nàge.","This isn't as good as that one."],
  ["擦","cā","v.","to wipe; to rub","请擦干净桌子。","Qǐng cā gānjìng zhuōzi.","Please wipe the table clean."],
  ["猜","cāi","v.","to guess","你猜猜看。","Nǐ cāi cāi kàn.","Take a guess."],
  ["材料","cáiliào","n.","material; data","请准备好材料。","Qǐng zhǔnbèi hǎo cáiliào.","Please prepare the materials."],
  ["参观","cānguān","v.","to visit; to tour","我们去参观博物馆。","Wǒmen qù cānguān bówùguǎn.","We're visiting the museum."],
  ["参赛","cānsài","v.","to compete; to enter a contest","他要参赛。","Tā yào cānsài.","He's going to compete."],
  ["餐厅","cāntīng","n.","dining hall; restaurant","餐厅在二楼。","Cāntīng zài èr lóu.","The dining hall is on the second floor."],
  ["操场","cāochǎng","n.","playground; sports field","孩子们在操场上。","Háizimen zài cāochǎng shàng.","The kids are on the playground."],
  ["厕所","cèsuǒ","n.","toilet; restroom","厕所在哪儿？","Cèsuǒ zài nǎr?","Where's the restroom?"],
  ["查看","chákàn","v.","to look over; to check","请查看邮件。","Qǐng chákàn yóujiàn.","Please check the email."],
  ["茶叶","cháyè","n.","tea leaves","我买了一些茶叶。","Wǒ mǎi le yìxiē cháyè.","I bought some tea leaves."],
  ["查找","cházhǎo","v.","to search; to look up","我在查找答案。","Wǒ zài cházhǎo dá'àn.","I'm searching for the answer."],
  ["差点儿","chàdiǎnr","adj.","almost; nearly","我差点儿迟到。","Wǒ chàdiǎnr chídào.","I was almost late."],
  ["产生","chǎnshēng","v.","to produce; to arise","这会产生问题。","Zhè huì chǎnshēng wèntí.","This will cause problems."],
  ["厂","chǎng","n.","factory","他在工厂工作。","Tā zài gōngchǎng gōngzuò.","He works at the factory."],
  ["场","chǎng","m.w.","(measure word for events)","我们看了一场电影。","Wǒmen kàn le yì chǎng diànyǐng.","We saw a movie."],
  ["超过","chāoguò","v.","to exceed; to surpass","速度超过了限制。","Sùdù chāoguò le xiànzhì.","The speed exceeded the limit."],
  ["车速","chēsù","n.","vehicle speed","请注意车速。","Qǐng zhùyì chēsù.","Please mind your speed."],
  ["车位","chēwèi","n.","parking space","这里没有车位。","Zhèlǐ méiyǒu chēwèi.","There's no parking here."],
  ["城","chéng","n.","city; town","这座城很大。","Zhè zuò chéng hěn dà.","This city is big."],
  ["乘","chéng","v.","to multiply; to ride","二乘三是六。","Èr chéng sān shì liù.","Two times three is six."],
  ["成功","chénggōng","v.","to succeed; successful","他成功了。","Tā chénggōng le.","He succeeded."],
  ["乘客","chéngkè","n.","passenger","乘客请上车。","Chéngkè qǐng shàng chē.","Passengers please board."],
  ["诚实","chéngshí","adj.","honest","他是诚实的人。","Tā shì chéngshí de rén.","He is an honest person."],
  ["成为","chéngwéi","v.","to become","她成为了医生。","Tā chéngwéi le yīshēng.","She became a doctor."],
  ["乘坐","chéngzuò","v.","to ride; to take (transport)","我乘坐地铁去。","Wǒ chéngzuò dìtiě qù.","I take the subway."],
  ["吃惊","chījīng","v.","to be startled; surprised","我很吃惊。","Wǒ hěn chījīng.","I'm very surprised."],
  ["迟","chí","adj.","late; tardy","你来得太迟了。","Nǐ lái de tài chí le.","You came too late."],
  ["重","chóng","adv.","again; once more","请重做一次。","Qǐng chóng zuò yí cì.","Please do it again."],
  ["重新","chóngxīn","adv.","again; anew","我们重新开始。","Wǒmen chóngxīn kāishǐ.","Let's start over."],
  ["出差","chūchāi","v.","to go on a business trip","他下周出差。","Tā xià zhōu chūchāi.","He's on a business trip next week."],
  ["出口","chūkǒu","n.","exit","出口在那边。","Chūkǒu zài nàbiān.","The exit is over there."],
  ["出现","chūxiàn","v.","to appear; to emerge","他突然出现了。","Tā tūrán chūxiàn le.","He suddenly appeared."],
  ["出行","chūxíng","v.","to travel; to go out","今天不适合出行。","Jīntiān bú shìhé chūxíng.","Today isn't good for traveling."],
  ["出租","chūzū","v.","to rent out","这房子出租。","Zhè fángzi chūzū.","This house is for rent."],
  ["厨房","chúfáng","n.","kitchen","她在厨房做饭。","Tā zài chúfáng zuò fàn.","She is cooking in the kitchen."],
  ["厨师","chúshī","n.","chef; cook","他是有名的厨师。","Tā shì yǒumíng de chúshī.","He is a famous chef."],
  ["窗","chuāng","n.","window","请打开窗。","Qǐng dǎkāi chuāng.","Please open the window."],
  ["窗户","chuānghu","n.","window","窗户开着呢。","Chuānghu kāi zhe ne.","The window is open."],
  ["吹","chuī","v.","to blow","风吹得很大。","Fēng chuī de hěn dà.","The wind blows strongly."],
  ["词语","cíyǔ","n.","word; vocabulary","这个词语很有用。","Zhège cíyǔ hěn yǒuyòng.","This word is very useful."],
  ["此","cǐ","pron.","this","此地很美。","Cǐ dì hěn měi.","This place is beautiful."],
  ["此次","cǐcì","phrase","this time","此次会议很重要。","Cǐcì huìyì hěn zhòngyào.","This meeting is important."],
  ["此外","cǐwài","conj.","besides; in addition","此外，还有别的。","Cǐwài, hái yǒu bié de.","Besides, there's more."],
  ["从此","cóngcǐ","adv.","from now on","从此他没回来。","Cóngcǐ tā méi huílái.","From then on he didn't return."],
  ["从来","cónglái","adv.","ever; never (negated)","我从来不喝酒。","Wǒ cónglái bù hē jiǔ.","I never drink alcohol."],
  ["从中","cóngzhōng","adv.","from (within); from it","我从中学了很多。","Wǒ cóngzhōng xué le hěn duō.","I learned a lot from it."],
  ["粗","cū","adj.","thick; coarse","这根线太粗。","Zhè gēn xiàn tài cū.","This thread is too thick."],
  ["粗心","cūxīn","adj.","careless","他做事很粗心。","Tā zuòshì hěn cūxīn.","He's careless in his work."],
  ["村","cūn","n.","village","这个村很小。","Zhège cūn hěn xiǎo.","This village is small."],
  ["存","cún","v.","to store; to save","我存了一些钱。","Wǒ cún le yìxiē qián.","I saved some money."],
  ["错过","cuòguò","v.","to miss (an opportunity)","我错过了机会。","Wǒ cuòguò le jīhuì.","I missed the chance."],
  ["错误","cuòwù","adj.","wrong; mistake","这是个错误。","Zhè shì gè cuòwù.","This is a mistake."],
  ["答应","dāying","v.","to agree; to promise","他答应来。","Tā dāying lái.","He agreed to come."],
  ["答","dá","v.","to answer; to reply","请答这个问题。","Qǐng dá zhège wèntí.","Please answer this question."],
  ["答案","dá’àn","n.","answer","答案在书后。","Dá'àn zài shū hòu.","The answer is at the back of the book."],
  ["达到","dádào","v.","to reach; to achieve","我达到了目标。","Wǒ dádào le mùbiāo.","I reached the goal."],
  ["打招呼","dǎzhāohu","v.","to greet","我跟他打招呼。","Wǒ gēn tā dǎzhāohu.","I greeted him."],
  ["打败","dǎbài","v.","to defeat","我们打败了对手。","Wǒmen dǎbài le duìshǒu.","We defeated the opponent."],
  ["打工","dǎgōng","v.","to work part-time","他暑假打工。","Tā shǔjià dǎgōng.","He works part-time in summer."],
  ["打扰","dǎrǎo","v.","to disturb; to bother","对不起，打扰了。","Duìbuqǐ, dǎrǎo le.","Sorry to disturb you."],
  ["打印","dǎyìn","v.","to print","请打印这份文件。","Qǐng dǎyìn zhè fèn wénjiàn.","Please print this document."],
  ["打印机","dǎyìnjī","n.","printer","打印机坏了。","Dǎyìnjī huài le.","The printer is broken."],
  ["打折","dǎzhé","v.","to give a discount","这家店在打折。","Zhè jiā diàn zài dǎzhé.","This shop is having a sale."],
  ["打针","dǎzhēn","v.","to get an injection","他怕打针。","Tā pà dǎzhēn.","He's afraid of injections."],
  ["大巴","dàbā","n.","coach (bus)","我们坐大巴去。","Wǒmen zuò dàbā qù.","We're going by coach."],
  ["大大","dàdà","adv.","greatly; enormously","大大减少了。","Dàdà jiǎnshǎo le.","Greatly reduced."],
  ["大夫","dàifu","n.","doctor","大夫，我感冒了。","Dàifu, wǒ gǎnmào le.","Doctor, I have a cold."],
  ["大量","dàliàng","adj.","large amount","他买了大量的书。","Tā mǎi le dàliàng de shū.","He bought lots of books."],
  ["大赛","dàsài","n.","major contest","他参加了大赛。","Tā cānjiā le dàsài.","He joined the big contest."],
  ["大厅","dàtīng","n.","hall; lobby","我在大厅等你。","Wǒ zài dàtīng děng nǐ.","I'll wait in the lobby."],
  ["大约","dàyuē","adv.","about; approximately","大约十点到。","Dàyuē shí diǎn dào.","Arrives about ten o'clock."],
  ["大自然","dàzìrán","n.","nature","我喜欢大自然。","Wǒ xǐhuan dàzìrán.","I love nature."],
  ["待","dāi","v.","to stay","我想在家待一天。","Wǒ xiǎng zài jiā dāi yì tiān.","I want to stay home a day."],
  ["戴","dài","v.","to wear (accessory)","他戴着眼镜。","Tā dài zhe yǎnjìng.","He's wearing glasses."],
  ["袋子","dàizi","n.","bag; sack","请用袋子装。","Qǐng yòng dàizi zhuāng.","Please put it in a bag."],
  ["单位","dānwèi","n.","work unit; organization","他的单位很大。","Tā de dānwèi hěn dà.","His workplace is big."],
  ["当","dāng","v.","to serve as; when","他当老师。","Tā dāng lǎoshī.","He works as a teacher."],
  ["当时","dāngshí","n.","at that time","当时我不在。","Dāngshí wǒ bú zài.","I wasn't there at the time."],
  ["刀","dāo","n.","knife","请给我一把刀。","Qǐng gěi wǒ yì bǎ dāo.","Please give me a knife."],
  ["导游","dǎoyóu","v.","tour guide; to guide","他是导游。","Tā shì dǎoyóu.","He is a tour guide."],
  ["倒","dào","v.","to pour; to fall","请给我倒水。","Qǐng gěi wǒ dào shuǐ.","Please pour me some water."],
  ["道","dào","n.","way; road; (m.w. for dishes)","我点了两道菜。","Wǒ diǎn le liǎng dào cài.","I ordered two dishes."],
  ["到底","dàodǐ","adv.","after all; in the end","你到底想什么？","Nǐ dàodǐ xiǎng shénme?","What do you really want?"],
  ["到来","dàolái","v.","to arrive; arrival","春天到来了。","Chūntiān dàolái le.","Spring has arrived."],
  ["道路","dàolù","n.","road; path","这条道路很宽。","Zhè tiáo dàolù hěn kuān.","This road is wide."],
  ["道歉","dàoqiàn","v.","to apologize","他向我道歉。","Tā xiàng wǒ dàoqiàn.","He apologized to me."],
  ["得意","déyì","adj.","pleased with oneself","他得意地笑了。","Tā déyì de xiào le.","He smiled smugly."],
  ["登机","dēngjī","v.","to board a plane","现在开始登机。","Xiànzài kāishǐ dēngjī.","Boarding starts now."],
  ["等","děng","part.","etc.; and so on","我喜欢苹果、橘子等。","Wǒ xǐhuan píngguǒ, júzi děng.","I like apples, oranges, etc."],
  ["等到","děngdào","prep.","until; by the time","等到明天再说。","Děngdào míngtiān zài shuō.","Wait until tomorrow."],
  ["低","dī","adj.","low","声音太低了。","Shēngyīn tài dī le.","The sound is too low."],
  ["低价","dījià","n.","low price","我们以低价买的。","Wǒmen yǐ dījià mǎi de.","We bought it at a low price."],
  ["低温","dīwēn","n.","low temperature","今天低温五度。","Jīntiān dīwēn wǔ dù.","Today's low is five degrees."],
  ["低于","dīyú","v.","lower than","价格低于市场。","Jiàgé dīyú shìchǎng.","The price is below market."],
  ["底","dǐ","n.","bottom; end","杯底有水。","Bēi dǐ yǒu shuǐ.","There's water at the cup's bottom."],
  ["底下","dǐxia","n.","underneath; below","桌子底下有猫。","Zhuōzi dǐxia yǒu māo.","There's a cat under the table."],
  ["地球","dìqiú","n.","Earth; globe","地球只有一个。","Dìqiú zhǐ yǒu yí gè.","There's only one Earth."],
  ["地址","dìzhǐ","n.","address","请写下地址。","Qǐng xiě xià dìzhǐ.","Please write down the address."],
  ["点名","diǎnmíng","v.","to take attendance","老师点名了。","Lǎoshī diǎnmíng le.","The teacher took attendance."],
  ["点头","diǎntóu","v.","to nod","他点头同意。","Tā diǎntóu tóngyì.","He nodded in agreement."],
  ["电动车","diàndòngchē","n.","electric vehicle","他骑电动车上班。","Tā qí diàndòngchē shàngbān.","He rides an e-bike to work."],
  ["电视剧","diànshìjù","n.","TV drama","我爱看电视剧。","Wǒ ài kàn diànshìjù.","I love TV dramas."],
  ["掉","diào","v.","to fall; to drop","钱包掉了。","Qiánbāo diào le.","The wallet fell."],
  ["调查","diàochá","v.","to investigate; survey","警察在调查。","Jǐngchá zài diàochá.","The police are investigating."],
  ["订","dìng","v.","to book; to order","我订了机票。","Wǒ dìng le jīpiào.","I booked the ticket."],
  ["定","dìng","v.","to decide; to set","时间定了。","Shíjiān dìng le.","The time is set."],
  ["东部","dōngbù","n.","eastern part","他住在东部。","Tā zhù zài dōngbù.","He lives in the east."],
  ["动车","dòngchē","n.","bullet train","我坐动车去。","Wǒ zuò dòngchē qù.","I'll take the bullet train."],
  ["动作","dòngzuò","n.","action; movement","这个动作难。","Zhège dòngzuò nán.","This movement is hard."],
  ["读者","dúzhě","n.","reader","亲爱的读者们。","Qīn'ài de dúzhě men.","Dear readers."],
  ["堵车","dǔchē","v.","traffic jam","上班路上堵车。","Shàngbān lù shàng dǔchē.","There's a jam on the way to work."],
  ["度假","dùjià","v.","to vacation","我们去海边度假。","Wǒmen qù hǎibiān dùjià.","We're vacationing at the beach."],
  ["肚子","dùzi","n.","belly; stomach","我肚子疼。","Wǒ dùzi téng.","My stomach hurts."],
  ["短信","duǎnxìn","n.","text message","他给我发短信。","Tā gěi wǒ fā duǎnxìn.","He sent me a text."],
  ["队","duì","n.","team; line","我们队赢了。","Wǒmen duì yíng le.","Our team won."],
  ["对方","duìfāng","n.","the other side; opponent","对方还没回复。","Duìfāng hái méi huífù.","The other side hasn't replied."],
  ["对面","duìmiàn","n.","opposite side; across","对面是银行。","Duìmiàn shì yínháng.","The bank is across."],
  ["对于","duìyú","prep.","regarding; with respect to","对于这件事，我同意。","Duìyú zhè jiàn shì, wǒ tóngyì.","Regarding this, I agree."],
  ["队员","duìyuán","n.","team member","他是新队员。","Tā shì xīn duìyuán.","He's a new team member."],
  ["队长","duìzhǎng","n.","team captain","她是我们的队长。","Tā shì wǒmen de duìzhǎng.","She's our captain."],
  ["顿","dùn","m.w.","(m.w. for meals)","我吃了一顿饭。","Wǒ chī le yí dùn fàn.","I had a meal."],
  ["多么","duōme","adv.","how; what","多么美丽啊！","Duōme měilì a!","How beautiful!"],
  ["多数","duōshù","n.","majority","多数人同意。","Duōshù rén tóngyì.","The majority agrees."],
  ["多样","duōyàng","adj.","diverse; various","文化是多样的。","Wénhuà shì duōyàng de.","Culture is diverse."],
  ["而","ér","conj.","and; but; yet","他笑而不答。","Tā xiào ér bù dá.","He smiled and did not answer."],
  ["儿童","értóng","n.","children","公园里有儿童。","Gōngyuán lǐ yǒu értóng.","There are kids at the park."],
  ["发出","fāchū","v.","to emit; to issue","他发出了声音。","Tā fāchū le shēngyīn.","He made a sound."],
  ["发送","fāsòng","v.","to send (a message)","我发送了邮件。","Wǒ fāsòng le yóujiàn.","I sent the email."],
  ["法","fǎ","n.","law; method","我有办法。","Wǒ yǒu bànfǎ.","I have a method."],
  ["法律","fǎlǜ","n.","law","我学法律。","Wǒ xué fǎlǜ.","I study law."],
  ["翻译","fānyì","v.","to translate; translator","请帮我翻译。","Qǐng bāng wǒ fānyì.","Please help me translate."],
  ["烦","fán","adj.","annoyed; bothered","别烦我！","Bié fán wǒ!","Don't bother me!"],
  ["烦恼","fánnǎo","adj.","worried; troubled","我有烦恼。","Wǒ yǒu fánnǎo.","I have worries."],
  ["反对","fǎnduì","v.","to oppose","我反对这个计划。","Wǒ fǎnduì zhège jìhuà.","I oppose this plan."],
  ["方面","fāngmiàn","n.","aspect; side","在这方面他很强。","Zài zhè fāngmiàn tā hěn qiáng.","He's strong in this area."],
  ["方式","fāngshì","n.","way; manner","这种方式不好。","Zhè zhǒng fāngshì bù hǎo.","This way isn't good."],
  ["房东","fángdōng","n.","landlord","房东很友好。","Fángdōng hěn yǒuhǎo.","The landlord is friendly."],
  ["房租","fángzū","n.","rent","这里房租贵。","Zhèlǐ fángzū guì.","Rent here is expensive."],
  ["放弃","fàngqì","v.","to give up","别放弃！","Bié fàngqì!","Don't give up!"],
  ["放松","fàngsōng","v.","to relax","你需要放松。","Nǐ xūyào fàngsōng.","You need to relax."],
  ["费","fèi","n.","fee; to spend","学费要交。","Xuéfèi yào jiāo.","Tuition must be paid."],
  ["费用","fèiyong","n.","expense; cost","费用我来付。","Fèiyong wǒ lái fù.","I'll pay the expense."],
  ["分数","fēnshù","n.","","","",""],
  ["分为","fēnwéi","v.","","","",""],
  ["份","fèn","m.w.","","","",""],
  ["丰富","fēngfù","adj.","","","",""],
  ["风景","fēngjǐng","n.","","","",""],
  ["否则","fǒuzé","conj.","","","",""],
  ["幅","fú","m.w.","","","",""],
  ["符合","fúhé","v.","","","",""],
  ["付","fù","v.","","","",""],
  ["父母","fùmǔ","n.","","","",""],
  ["父女","fùnǚ","n.","","","",""],
  ["父亲","fùqīn","n.","","","",""],
  ["复印","fùyìn","v.","","","",""],
  ["复杂","fùzá","adj.","","","",""],
  ["负责","fùzé","v.","","","",""],
  ["负责人","fùzérén","n.","","","",""],
  ["父子","fùzǐ","n.","","","",""],
  ["改","gǎi","v.","","","",""],
  ["改变","gǎibiàn","v.","","","",""],
  ["干","gān","adj.","","","",""],
  ["干杯","gānbēi","v.","","","",""],
  ["赶","gǎn","v.","","","",""],
  ["敢","gǎn","v.","","","",""],
  ["感","gǎn","suffix","","","",""],
  ["感动","gǎndòng","adj.","","","",""],
  ["赶紧","gǎnjǐn","adv.","","","",""],
  ["感觉","gǎnjué","n.","","","",""],
  ["赶快","gǎnkuài","adv.","","","",""],
  ["感情","gǎnqíng","n.","","","",""],
  ["感人","gǎnrén","adj.","","","",""],
  ["赶上","gǎnshàng","v.","","","",""],
  ["感受","gǎnshòu","v.","","","",""],
  ["感谢","gǎnxiè","v.","","","",""],
  ["干活儿","gànhuór","v.","","","",""],
  ["钢琴","gāngqín","n.","","","",""],
  ["高价","gāojià","n.","","","",""],
  ["高考","gāokǎo","n.","","","",""],
  ["高速","gāosù","adj.","","","",""],
  ["高温","gāowēn","n.","","","",""],
  ["高于","gāoyú","v.","","","",""],
  ["胳膊","gēbo","n.","","","",""],
  ["歌声","gēshēng","n.","","","",""],
  ["歌手","gēshǒu","n.","","","",""],
  ["各","gè","pron.","","","",""],
  ["各地","gèdì","n.","","","",""],
  ["各个","gègè","pron.","","","",""],
  ["各位","gèwèi","pron.","","","",""],
  ["各种","gèzhǒng","pron.","","","",""],
  ["更加","gèngjiā","adv.","","","",""],
  ["工厂","gōngchǎng","n.","","","",""],
  ["功夫","gōngfu","n.","","","",""],
  ["公共","gōnggòng","adj.","","","",""],
  ["功课","gōngkè","n.","","","",""],
  ["公里","gōnglǐ","m.w.","","","",""],
  ["公路","gōnglù","n.","","","",""],
  ["工人","gōngrén","n.","","","",""],
  ["工资","gōngzī","n.","","","",""],
  ["共","gòng","adv.","","","",""],
  ["共同","gòngtóng","adj.","","","",""],
  ["够","gòu","v.","","","",""],
  ["购买","gòumǎi","v.","","","",""],
  ["购物","gòuwù","v.","","","",""],
  ["估计","gūjì","v.","","","",""],
  ["姑娘","gūniang","n.","","","",""],
  ["鼓励","gǔlì","v.","","","",""],
  ["顾客","gùkè","n.","","","",""],
  ["故意","gùyì","adv.","","","",""],
  ["挂","guà","v.","","","",""],
  ["关键","guānjiàn","n.","","","",""],
  ["观看","guānkàn","v.","","","",""],
  ["观众","guānzhòng","n.","","","",""],
  ["管","guǎn","v.","","","",""],
  ["管理","guǎnlǐ","v.","","","",""],
  ["光","guāng","n.","","","",""],
  ["广播","guǎngbō","v.","","","",""],
  ["广告","guǎnggào","n.","","","",""],
  ["逛","guàng","v.","","","",""],
  ["规定","guīdìng","v.","","","",""],
  ["国籍","guójí","n.","","","",""],
  ["国际","guójì","adj.","","","",""],
  ["果汁","guǒzhī","n.","","","",""],
  ["过程","guòchéng","n.","","","",""],
  ["海洋","hǎiyáng","n.","","","",""],
  ["害羞","hàixiū","adj.","","","",""],
  ["寒假","hánjià","n.","","","",""],
  ["寒冷","hánlěng","adj.","","","",""],
  ["喊","hǎn","v.","","","",""],
  ["汗","hàn","n.","","","",""],
  ["航班","hángbān","n.","","","",""],
  ["好处","hǎochù","n.","","","",""],
  ["好好","hǎohǎo","adj.","","","",""],
  ["好笑","hǎoxiào","adj.","","","",""],
  ["合格","hégé","adj.","","","",""],
  ["盒子","hézi","n.","","","",""],
  ["红包","hóngbāo","n.","","","",""],
  ["厚","hòu","adj.","","","",""],
  ["后悔","hòuhuǐ","v.","","","",""],
  ["忽然","hūrán","adv.","","","",""],
  ["互联网","hùliánwǎng","n.","","","",""],
  ["护士","hùshi","n.","","","",""],
  ["互相","hùxiāng","adv.","","","",""],
  ["话剧","huàjù","n.","","","",""],
  ["怀疑","huáiyí","v.","","","",""],
  ["坏处","huàichù","n.","","","",""],
  ["环保","huánbǎo","n.","","","",""],
  ["换乘","huànchéng","v.","","","",""],
  ["回复","huífù","v.","","","",""],
  ["回信","huíxìn","v.","","","",""],
  ["回忆","huíyì","v.","","","",""],
  ["会员","huìyuán","n.","","","",""],
  ["活","huó","v.","","","",""],
  ["活动","huódòng","v.","","","",""],
  ["活泼","huópō","adj.","","","",""],
  ["火","huǒ","n.","","","",""],
  ["货","huò","n.","","","",""],
  ["获得","huòdé","v.","","","",""],
  ["获奖","huòjiǎng","v.","","","",""],
  ["获取","huòqǔ","v.","","","",""],
  ["基本","jīběn","adj.","","","",""],
  ["基本上","jīběnshàng","adv.","","","",""],
  ["基础","jīchǔ","n.","","","",""],
  ["激动","jīdòng","adj.","","","",""],
  ["积极","jījí","adj.","","","",""],
  ["积累","jīlěi","v.","","","",""],
  ["及时","jíshí","adj.","","","",""],
  ["即使","jíshǐ","conj.","","","",""],
  ["既","jì","adv.","","","",""],
  ["寄","jì","v.","","","",""],
  ["计划","jìhuà","n.","","","",""],
  ["既然","jìrán","conj.","","","",""],
  ["技术","jìshù","n.","","","",""],
  ["继续","jìxù","v.","","","",""],
  ["记者","jìzhě","n.","","","",""],
  ["加班","jiābān","v.","","","",""],
  ["家具","jiājù","n.","","","",""],
  ["加快","jiākuài","v.","","","",""],
  ["加强","jiāqiáng","v.","","","",""],
  ["加入","jiārù","v.","","","",""],
  ["加上","jiāshàng","conj.","","","",""],
  ["家庭","jiātíng","n.","","","",""],
  ["家乡","jiāxiāng","n.","","","",""],
  ["加油","jiāyóu","v.","","","",""],
  ["加油站","jiāyóuzhàn","n.","","","",""],
  ["家长","jiāzhǎng","n.","","","",""],
  ["假","jiǎ","adj.","","","",""],
  ["价格","jiàgé","n.","","","",""],
  ["价钱","jiàqián","n.","","","",""],
  ["假日","jiàrì","n.","","","",""],
  ["减","jiǎn","v.","","","",""],
  ["减轻","jiǎnqīng","v.","","","",""],
  ["减少","jiǎnshǎo","v.","","","",""],
  ["健身","jiànshēn","v.","","","",""],
  ["健身房","jiànshēnfáng","n.","","","",""],
  ["建议","jiànyì","v.","","","",""],
  ["江","jiāng","n.","","","",""],
  ["将","jiāng","prep.","","","",""],
  ["将来","jiānglái","n.","","","",""],
  ["将要","jiāngyào","adv.","","","",""],
  ["奖","jiǎng","n.","","","",""],
  ["奖金","jiǎngjīn","n.","","","",""],
  ["奖学金","jiǎngxuéjīn","n.","","","",""],
  ["降","jiàng","v.","","","",""],
  ["降低","jiàngdī","v.","","","",""],
  ["降价","jiàngjià","v.","","","",""],
  ["降落","jiàngluò","v.","","","",""],
  ["降温","jiàngwēn","v.","","","",""],
  ["交","jiāo","v.","","","",""],
  ["骄傲","jiāo’ào","adj.","","","",""],
  ["交警","jiāojǐng","n.","","","",""],
  ["交流","jiāoliú","v.","","","",""],
  ["郊区","jiāoqū","n.","","","",""],
  ["交通","jiāotōng","n.","","","",""],
  ["教练","jiàoliàn","n.","","","",""],
  ["教师","jiàoshī","n.","","","",""],
  ["教授","jiàoshòu","n.","","","",""],
  ["教学","jiàoxué","n.","","","",""],
  ["教育","jiàoyù","n.","","","",""],
  ["叫作","jiàozuò","v.","","","",""],
  ["街道","jiēdào","n.","","","",""],
  ["接受","jiēshòu","v.","","","",""],
  ["接着","jiēzhe","v.","","","",""],
  ["结果","jiéguǒ","n.","","","",""],
  ["节假日","jiéjiàrì","n.","","","",""],
  ["节约","jiéyuē","v.","","","",""],
  ["结账","jiézhàng","v.","","","",""],
  ["解释","jiěshì","v.","","","",""],
  ["今后","jīnhòu","n.","","","",""],
  ["仅","jǐn","adv.","","","",""],
  ["尽管","jǐnguǎn","adv.","","","",""],
  ["仅仅","jǐnjǐn","adv.","","","",""],
  ["紧张","jǐnzhāng","adj.","","","",""],
  ["进入","jìnrù","v.","","","",""],
  ["进行","jìnxíng","v.","","","",""],
  ["禁止","jìnzhǐ","v.","","","",""],
  ["精彩","jīngcǎi","adj.","","","",""],
  ["经济","jīngjì","n.","","","",""],
  ["京剧","jīngjù","n.","","","",""],
  ["经历","jīnglì","v.","","","",""],
  ["经验","jīngyàn","n.","","","",""],
  ["警察","jǐngchá","n.","","","",""],
  ["景点","jǐngdiǎn","n.","","","",""],
  ["景区","jǐngqū","n.","","","",""],
  ["景色","jǐngsè","n.","","","",""],
  ["竟然","jìngrán","adv.","","","",""],
  ["竞争","jìngzhēng","v.","","","",""],
  ["镜子","jìngzi","n.","","","",""],
  ["究竟","jiūjìng","adv.","","","",""],
  ["就是","jiùshì","part.","","","",""],
  ["举","jǔ","v.","","","",""],
  ["举办","jǔbàn","v.","","","",""],
  ["举例","jǔlì","v.","","","",""],
  ["举行","jǔxíng","v.","","","",""],
  ["聚","jù","v.","","","",""],
  ["聚餐","jùcān","v.","","","",""],
  ["聚会","jùhuì","v.","","","",""],
  ["拒绝","jùjué","v.","","","",""],
  ["距离","jùlí","v.","","","",""],
  ["剧院","jùyuàn","n.","","","",""],
  ["开玩笑","kāiwánxiào","v.","","","",""],
  ["看法","kànfǎ","n.","","","",""],
  ["烤","kǎo","v.","","","",""],
  ["考虑","kǎolǜ","v.","","","",""],
  ["考生","kǎoshēng","n.","","","",""],
  ["棵","kē","m.w.","","","",""],
  ["科技","kējì","n.","","","",""],
  ["科学","kēxué","n.","","","",""],
  ["咳","ké","v.","","","",""],
  ["咳嗽","késou","v.","","","",""],
  ["可惜","kěxī","adj.","","","",""],
  ["克","kè","m.w.","","","",""],
  ["课程","kèchéng","n.","","","",""],
  ["客气","kèqi","adj.","","","",""],
  ["课堂","kètáng","n.","","","",""],
  ["客厅","kètīng","n.","","","",""],
  ["肯定","kěndìng","v.","","","",""],
  ["空","kōng","adj.","","","",""],
  ["空气","kōngqì","n.","","","",""],
  ["恐怕","kǒngpà","v.","","","",""],
  ["空","kòng","v.","","","",""],
  ["口语","kǒuyǔ","n.","","","",""],
  ["苦","kǔ","adj.","","","",""],
  ["快餐","kuàicān","n.","","","",""],
  ["快递","kuàidì","n.","","","",""],
  ["快速","kuàisù","adj.","","","",""],
  ["困","kùn","adj.","","","",""],
  ["困难","kùnnan","adj.","","","",""],
  ["拉","lā","v.","","","",""],
  ["垃圾","lājī","n.","","","",""],
  ["辣","là","adj.","","","",""],
  ["来不及","láibují","v.","","","",""],
  ["来得及","láidejí","v.","","","",""],
  ["懒","lǎn","adj.","","","",""],
  ["浪费","làngfèi","v.","","","",""],
  ["浪漫","làngmàn","adj.","","","",""],
  ["老虎","lǎohǔ","n.","","","",""],
  ["老家","lǎojiā","n.","","","",""],
  ["老年","lǎonián","n.","","","",""],
  ["老是","lǎoshì","adv.","","","",""],
  ["冷静","lěngjìng","adj.","","","",""],
  ["理发","lǐfà","v.","","","",""],
  ["理解","lǐjiě","v.","","","",""],
  ["礼貌","lǐmào","n.","","","",""],
  ["理想","lǐxiǎng","n.","","","",""],
  ["厉害","lìhai","adj.","","","",""],
  ["力气","lìqi","n.","","","",""],
  ["例如","lìrú","v.","","","",""],
  ["例子","lìzi","n.","","","",""],
  ["俩","liǎ","num.","","","",""],
  ["连","lián","prep.","","","",""],
  ["联系","liánxì","v.","","","",""],
  ["凉","liáng","adj.","","","",""],
  ["量","liáng","v.","","","",""],
  ["两","liǎng","m.w.","","","",""],
  ["亮","liàng","adj.","","","",""],
  ["列","liè","v.","","","",""],
  ["零下","língxià","phrase","","","",""],
  ["零花钱","línghuāqián","n.","","","",""],
  ["零钱","língqián","n.","","","",""],
  ["零食","língshí","n.","","","",""],
  ["另","lìng","pron.","","","",""],
  ["另外","lìngwài","pron.","","","",""],
  ["留","liú","v.","","","",""],
  ["流","liú","v.","","","",""],
  ["流利","liúlì","adj.","","","",""],
  ["留下","liúxia","v.","","","",""],
  ["流行","liúxíng","v.","","","",""],
  ["路过","lùguò","v.","","","",""],
  ["旅馆","lǚguǎn","n.","","","",""],
  ["旅客","lǚkè","n.","","","",""],
  ["旅行","lǚxíng","v.","","","",""],
  ["律师","lǜshī","n.","","","",""],
  ["乱","luàn","adj.","","","",""],
  ["落","luò","v.","","","",""],
  ["麻烦","máfan","adj.","","","",""],
  ["馒头","mántou","n.","","","",""],
  ["满","mǎn","adj.","","","",""],
  ["毛巾","máojīn","n.","","","",""],
  ["毛衣","máoyī","n.","","","",""],
  ["帽子","màozi","n.","","","",""],
  ["美","měi","adj.","","","",""],
  ["美好","měihǎo","adj.","","","",""],
  ["美景","měijǐng","n.","","","",""],
  ["美丽","měilì","adj.","","","",""],
  ["美食","měishí","n.","","","",""],
  ["梦","mèng","n.","","","",""],
  ["梦想","mèngxiǎng","v.","","","",""],
  ["密码","mìmǎ","n.","","","",""],
  ["免费","miǎnfèi","v.","","","",""],
  ["面对","miànduì","v.","","","",""],
  ["面试","miànshì","v.","","","",""],
  ["秒","miǎo","m.w.","","","",""],
  ["民族","mínzú","n.","","","",""],
  ["末","mò","n.","","","",""],
  ["母女","mǔnǚ","n.","","","",""],
  ["母亲","mǔqīn","n.","","","",""],
  ["母子","mǔzǐ","n.","","","",""],
  ["目标","mùbiāo","n.","","","",""],
  ["目的","mùdì","n.","","","",""],
  ["目的地","mùdìdì","n.","","","",""],
  ["目前","mùqián","n.","","","",""],
  ["耐心","nàixīn","adj.","","","",""],
  ["南部","nánbù","n.","","","",""],
  ["难道","nándào","adv.","","","",""],
  ["男士","nánshì","n.","","","",""],
  ["难受","nánshòu","adj.","","","",""],
  ["难忘","nánwàng","v.","","","",""],
  ["男性","nánxìng","n.","","","",""],
  ["内","nèi","n.","","","",""],
  ["内容","nèiróng","n.","","","",""],
  ["内心","nèixīn","n.","","","",""],
  ["能否","néngfǒu","adv.","","","",""],
  ["能够","nénggòu","v.","","","",""],
  ["能力","nénglì","n.","","","",""],
  ["嗯","ǹg","interj.","","","",""],
  ["年底","niándǐ","n.","","","",""],
  ["年龄","niánlíng","n.","","","",""],
  ["农村","nóngcūn","n.","","","",""],
  ["弄","nòng","v.","","","",""],
  ["女性","nǚxìng","n.","","","",""],
  ["暖和","nuǎnhuo","adj.","","","",""],
  ["偶尔","ǒu’ěr","adv.","","","",""],
  ["拍","pāi","v.","","","",""],
  ["排","pái","v.","","","",""],
  ["牌","pái","n.","","","",""],
  ["排队","páiduì","v.","","","",""],
  ["排球","páiqiú","n.","","","",""],
  ["牌子","páizi","n.","","","",""],
  ["判断","pànduàn","v.","","","",""],
  ["陪","péi","v.","","","",""],
  ["批评","pīpíng","v.","","","",""],
  ["皮肤","pífū","n.","","","",""],
  ["脾气","píqi","n.","","","",""],
  ["皮鞋","píxié","n.","","","",""],
  ["篇","piān","n.","","","",""],
  ["片","piàn","n.","","","",""],
  ["乒乓球","pīngpāngqiú","n.","","","",""],
  ["平常","píngcháng","adj.","","","",""],
  ["破","pò","v.","","","",""],
  ["葡萄","pútao","n.","","","",""],
  ["葡萄酒","pútaojiǔ","n.","","","",""],
  ["普遍","pǔbiàn","adj.","","","",""],
  ["普通","pǔtōng","adj.","","","",""],
  ["普通话","pǔtōnghuà","n.","","","",""],
  ["期","qī","m.w.","","","",""],
  ["期末","qīmò","n.","","","",""],
  ["期中","qīzhōng","n.","","","",""],
  ["其次","qícì","pron.","","","",""],
  ["其中","qízhōng","n.","","","",""],
  ["起到","qǐdào","v.","","","",""],
  ["气","qì","n.","","","",""],
  ["气候","qìhòu","n.","","","",""],
  ["汽水","qìshuǐ","n.","","","",""],
  ["气温","qìwēn","n.","","","",""],
  ["千克","qiānkè","m.w.","","","",""],
  ["千万","qiānwàn","adv.","","","",""],
  ["签证","qiānzhèng","v.","","","",""],
  ["前方","qiánfāng","n.","","","",""],
  ["前后","qiánhòu","n.","","","",""],
  ["强","qiáng","adj.","","","",""],
  ["敲","qiāo","v.","","","",""],
  ["桥","qiáo","n.","","","",""],
  ["巧","qiǎo","adj.","","","",""],
  ["巧克力","qiǎokèlì","n.","","","",""],
  ["亲戚","qīnqi","n.","","","",""],
  ["琴","qín","n.","","","",""],
  ["轻","qīng","adj.","","","",""],
  ["青年","qīngnián","n.","","","",""],
  ["轻松","qīngsōng","adj.","","","",""],
  ["情况","qíngkuàng","n.","","","",""],
  ["庆祝","qìngzhù","v.","","","",""],
  ["球队","qiúduì","n.","","","",""],
  ["球迷","qiúmí","n.","","","",""],
  ["区","qū","n.","","","",""],
  ["区别","qūbié","v.","","","",""],
  ["取","qǔ","v.","","","",""],
  ["取得","qǔdé","v.","","","",""],
  ["取消","qǔxiāo","v.","","","",""],
  ["全","quán","adj.","","","",""],
  ["全部","quánbù","n.","","","",""],
  ["全都","quándōu","adv.","","","",""],
  ["全球","quánqiú","n.","","","",""],
  ["全身","quánshēn","n.","","","",""],
  ["缺","quē","v.","","","",""],
  ["缺点","quēdiǎn","n.","","","",""],
  ["缺少","quēshǎo","v.","","","",""],
  ["却","què","adv.","","","",""],
  ["确实","quèshí","adv.","","","",""],
  ["然而","rán’ér","conj.","","","",""],
  ["热闹","rènao","adj.","","","",""],
  ["人生","rénshēng","n.","","","",""],
  ["人数","rénshù","n.","","","",""],
  ["人员","rényuán","n.","","","",""],
  ["任何","rènhé","pron.","","","",""],
  ["任务","rènwu","n.","","","",""],
  ["扔","rēng","v.","","","",""],
  ["仍","réng","adv.","","","",""],
  ["仍然","réngrán","adv.","","","",""],
  ["日常","rìcháng","adj.","","","",""],
  ["日记","rìjì","n.","","","",""],
  ["日期","rìqī","n.","","","",""],
  ["日子","rìzi","n.","","","",""],
  ["入","rù","v.","","","",""],
  ["入口","rùkǒu","n.","","","",""],
  ["入学","rùxué","v.","","","",""],
  ["入住","rùzhù","v.","","","",""],
  ["散步","sànbù","v.","","","",""],
  ["扫码","sǎomǎ","v.","","","",""],
  ["森林","sēnlín","n.","","","",""],
  ["商量","shāngliang","v.","","","",""],
  ["商品","shāngpǐn","n.","","","",""],
  ["伤心","shāngxīn","adj.","","","",""],
  ["上门","shàngmén","v.","","","",""],
  ["稍","shāo","adv.","","","",""],
  ["稍微","shāowēi","adv.","","","",""],
  ["少见","shǎojiàn","adj.","","","",""],
  ["少量","shǎoliàng","adj.","","","",""],
  ["少数","shǎoshù","n.","","","",""],
  ["少年","shàonián","n.","","","",""],
  ["社会","shèhuì","n.","","","",""],
  ["摄氏度","shèshìdù","m.w.","","","",""],
  ["身","shēn","n.","","","",""],
  ["深","shēn","adj.","","","",""],
  ["身份证","shēnfènzhèng","n.","","","",""],
  ["申请","shēnqǐng","v.","","","",""],
  ["甚至","shènzhì","conj.","","","",""],
  ["生","shēng","v.","","","",""],
  ["生","shēng","adj.","","","",""],
  ["生命","shēngmìng","n.","","","",""],
  ["生意","shēngyi","n.","","","",""],
  ["省","shěng","n.","","","",""],
  ["剩","shèng","v.","","","",""],
  ["失败","shībài","v.","","","",""],
  ["师傅","shīfu","n.","","","",""],
  ["失去","shīqù","v.","","","",""],
  ["师生","shīshēng","n.","","","",""],
  ["失望","shīwàng","v.","","","",""],
  ["十分","shífēn","adv.","","","",""],
  ["实际","shíjì","n.","","","",""],
  ["时间表","shíjiānbiǎo","n.","","","",""],
  ["实际上","shíjìshàng","adv.","","","",""],
  ["食品","shípǐn","n.","","","",""],
  ["食堂","shítáng","n.","","","",""],
  ["食物","shíwù","n.","","","",""],
  ["实在","shízài","adj.","","","",""],
  ["十字路口","shízìlùkǒu","n.","","","",""],
  ["使","shǐ","v.","","","",""],
  ["使馆","shǐguǎn","n.","","","",""],
  ["使用","shǐyòng","v.","","","",""],
  ["市场","shìchǎng","n.","","","",""],
  ["是否","shìfǒu","adv.","","","",""],
  ["适合","shìhé","v.","","","",""],
  ["世纪","shìjì","n.","","","",""],
  ["视频","shìpín","n.","","","",""],
  ["市区","shìqū","n.","","","",""],
  ["试题","shìtí","n.","","","",""],
  ["适应","shìyìng","v.","","","",""],
  ["收费","shōufèi","v.","","","",""],
  ["收入","shōurù","v.","","","",""],
  ["收拾","shōushi","v.","","","",""],
  ["收听","shōutīng","v.","","","",""],
  ["首","shǒu","m.w.","","","",""],
  ["首都","shǒudū","n.","","","",""],
  ["首先","shǒuxiān","adv.","","","",""],
  ["受不了","shòubuliǎo","v.","","","",""],
  ["售票员","shòupiàoyuán","n.","","","",""],
  ["受伤","shòushāng","v.","","","",""],
  ["输","shū","v.","","","",""],
  ["熟","shú/shóu","adj.","","","",""],
  ["熟悉","shúxi","v.","","","",""],
  ["暑假","shǔjià","n.","","","",""],
  ["数","shù","n.","","","",""],
  ["数量","shùliàng","n.","","","",""],
  ["树林","shùlín","n.","","","",""],
  ["数字","shùzì","n.","","","",""],
  ["帅","shuài","adj.","","","",""],
  ["顺便","shùnbiàn","adv.","","","",""],
  ["顺利","shùnlì","adj.","","","",""],
  ["顺序","shùnxù","n.","","","",""],
  ["说法","shuōfǎ","n.","","","",""],
  ["说明","shuōmíng","v.","","","",""],
  ["说明书","shuōmíngshū","n.","","","",""],
  ["硕士","shuòshì","n.","","","",""],
  ["死","sǐ","v.","","","",""],
  ["速度","sùdù","n.","","","",""],
  ["塑料","sùliào","n.","","","",""],
  ["酸","suān","adj.","","","",""],
  ["酸奶","suānnǎi","n.","","","",""],
  ["算","suàn","v.","","","",""],
  ["随便","suíbiàn","v.","","","",""],
  ["随着","suízhe","prep.","","","",""],
  ["孙女","sūnnǚ","n.","","","",""],
  ["孙子","sūnzi","n.","","","",""],
  ["所有","suǒyǒu","adj.","","","",""],
  ["台","tái","m.w.","","","",""],
  ["抬","tái","v.","","","",""],
  ["抬头","táitóu","v.","","","",""],
  ["态度","tàidù","n.","","","",""],
  ["弹","tán","v.","","","",""],
  ["谈","tán","v.","","","",""],
  ["汤","tāng","n.","","","",""],
  ["躺","tǎng","v.","","","",""],
  ["趟","tàng","m.w.","","","",""],
  ["讨论","tǎolùn","v.","","","",""],
  ["讨厌","tǎoyàn","adj.","","","",""],
  ["特点","tèdiǎn","n.","","","",""],
  ["提","tí","v.","","","",""],
  ["提出","tíchū","v.","","","",""],
  ["提到","tídào","v.","","","",""],
  ["提供","tígōng","v.","","","",""],
  ["提前","tíqián","v.","","","",""],
  ["提醒","tíxǐng","v.","","","",""],
  ["体检","tǐjiǎn","v.","","","",""],
  ["体温","tǐwēn","n.","","","",""],
  ["体重","tǐzhòng","n.","","","",""],
  ["填写","tiánxiě","v.","","","",""],
  ["条件","tiáojiàn","n.","","","",""],
  ["听力","tīnglì","n.","","","",""],
  ["听众","tīngzhòng","n.","","","",""],
  ["停","tíng","v.","","","",""],
  ["停车","tíngchē","v.","","","",""],
  ["停车场","tíngchēchǎng","n.","","","",""],
  ["停止","tíngzhǐ","v.","","","",""],
  ["通","tōng","v.","","","",""],
  ["通过","tōngguò","v.","","","",""],
  ["通知","tōngzhī","v.","","","",""],
  ["童年","tóngnián","n.","","","",""],
  ["同时","tóngshí","n.","","","",""],
  ["同样","tóngyàng","adj.","","","",""],
  ["桶","tǒng","n.","","","",""],
  ["痛","tòng","adj.","","","",""],
  ["头痛","tóutòng","adj.","","","",""],
  ["图","tú","n.","","","",""],
  ["图片","túpiàn","n.","","","",""],
  ["土","tǔ","n.","","","",""],
  ["推","tuī","v.","","","",""],
  ["推迟","tuīchí","v.","","","",""],
  ["推出","tuīchū","v.","","","",""],
  ["脱","tuō","v.","","","",""],
  ["袜子","wàzi","n.","","","",""],
  ["外出","wàichū","v.","","","",""],
  ["外套","wàitào","n.","","","",""],
  ["完全","wánquán","adj.","","","",""],
  ["晚安","wǎn’ān","v.","","","",""],
  ["晚餐","wǎncān","n.","","","",""],
  ["网购","wǎnggòu","v.","","","",""],
  ["往往","wǎngwǎng","adv.","","","",""],
  ["网页","wǎngyè","n.","","","",""],
  ["网友","wǎngyǒu","n.","","","",""],
  ["网址","wǎngzhǐ","n.","","","",""],
  ["危险","wēixiǎn","adj.","","","",""],
  ["为","wéi","v.","","","",""],
  ["味","wèi","n.","","","",""],
  ["味道","wèidào","n.","","","",""],
  ["卫生","wèishēng","adj.","","","",""],
  ["温度","wēndù","n.","","","",""],
  ["闻","wén","v.","","","",""],
  ["文件","wénjiàn","n.","","","",""],
  ["文章","wénzhāng","n.","","","",""],
  ["文字","wénzì","n.","","","",""],
  ["污染","wūrǎn","v.","","","",""],
  ["无","wú","v.","","","",""],
  ["无法","wúfǎ","v.","","","",""],
  ["无聊","wúliáo","adj.","","","",""],
  ["无论","wúlùn","conj.","","","",""],
  ["午餐","wǔcān","n.","","","",""],
  ["误会","wùhuì","v.","","","",""],
  ["吸","xī","v.","","","",""],
  ["西部","xībù","n.","","","",""],
  ["西红柿","xīhóngshì","n.","","","",""],
  ["吸引","xīyǐn","v.","","","",""],
  ["细","xì","adj.","","","",""],
  ["细心","xìxīn","adj.","","","",""],
  ["下降","xiàjiàng","v.","","","",""],
  ["鲜","xiān","adj.","","","",""],
  ["鲜花","xiānhuā","n.","","","",""],
  ["咸","xián","adj.","","","",""],
  ["现金","xiànjīn","n.","","","",""],
  ["羡慕","xiànmù","v.","","","",""],
  ["线上","xiànshàng","n.","","","",""],
  ["线下","xiànxià","n.","","","",""],
  ["现有","xiànyǒu","v.","","","",""],
  ["香","xiāng","adj.","","","",""],
  ["相比","xiāngbǐ","v.","","","",""],
  ["相反","xiāngfǎn","adj.","","","",""],
  ["相互","xiānghù","adv.","","","",""],
  ["相同","xiāngtóng","adj.","","","",""],
  ["详细","xiángxì","adj.","","","",""],
  ["响","xiǎng","v.","","","",""],
  ["想法","xiǎngfǎ","n.","","","",""],
  ["项","xiàng","m.w.","","","",""],
  ["消息","xiāoxi","n.","","","",""],
  ["小吃","xiǎochī","n.","","","",""],
  ["小伙子","xiǎohuǒzi","n.","","","",""],
  ["小说","xiǎoshuō","n.","","","",""],
  ["小组","xiǎozǔ","n.","","","",""],
  ["效果","xiàoguǒ","n.","","","",""],
  ["笑话","xiàohua","n.","","","",""],
  ["血","xiě","n.","","","",""],
  ["心","xīn","n.","","","",""],
  ["辛苦","xīnkǔ","adj.","","","",""],
  ["心情","xīnqíng","n.","","","",""],
  ["信号","xìnhào","n.","","","",""],
  ["信息","xìnxī","n.","","","",""],
  ["信心","xìnxīn","n.","","","",""],
  ["兴奋","xīngfèn","adj.","","","",""],
  ["星星","xīngxing","n.","","","",""],
  ["醒","xǐng","v.","","","",""],
  ["性","xìng","suffix","","","",""],
  ["性别","xìngbié","n.","","","",""],
  ["幸福","xìngfú","n.","","","",""],
  ["性格","xìnggé","n.","","","",""],
  ["兄弟","xiōngdì","n.","","","",""],
  ["熊","xióng","n.","","","",""],
  ["修","xiū","v.","","","",""],
  ["修理","xiūlǐ","v.","","","",""],
  ["许多","xǔduō","num.","","","",""],
  ["学费","xuéfèi","n.","","","",""],
  ["学院","xuéyuàn","n.","","","",""],
  ["压","yā","v.","","","",""],
  ["压力","yālì","n.","","","",""],
  ["牙膏","yágāo","n.","","","",""],
  ["亚洲","Yàzhōu","n.","","","",""],
  ["烟","yān","n.","","","",""],
  ["盐","yán","n.","","","",""],
  ["严格","yángé","adj.","","","",""],
  ["研究","yánjiū","v.","","","",""],
  ["研究生","yánjiūshēng","n.","","","",""],
  ["严重","yánzhòng","adj.","","","",""],
  ["演","yǎn","v.","","","",""],
  ["演唱","yǎnchàng","v.","","","",""],
  ["演出","yǎnchū","v.","","","",""],
  ["眼镜","yǎnjìng","n.","","","",""],
  ["眼前","yǎnqián","n.","","","",""],
  ["演员","yǎnyuán","n.","","","",""],
  ["阳光","yángguāng","n.","","","",""],
  ["养成","yǎngchéng","v.","","","",""],
  ["样子","yàngzi","n.","","","",""],
  ["邀请","yāoqǐng","v.","","","",""],
  ["要是","yàoshi","conj.","","","",""],
  ["钥匙","yàoshi","n.","","","",""],
  ["也许","yěxǔ","adv.","","","",""],
  ["夜","yè","n.","","","",""],
  ["夜晚","yèwǎn","n.","","","",""],
  ["叶子","yèzi","n.","","","",""],
  ["一切","yíqiè","pron.","","","",""],
  ["已","yǐ","adv.","","","",""],
  ["以内","yǐnèi","n.","","","",""],
  ["意见","yìjiàn","n.","","","",""],
  ["一生","yìshēng","n.","","","",""],
  ["艺术","yìshù","n.","","","",""],
  ["因此","yīncǐ","conj.","","","",""],
  ["引起","yǐnqǐ","v.","","","",""],
  ["印象","yìnxiàng","n.","","","",""],
  ["赢","yíng","v.","","","",""],
  ["赢得","yíngdé","v.","","","",""],
  ["应聘","yìngpìn","v.","","","",""],
  ["勇敢","yǒnggǎn","adj.","","","",""],
  ["永远","yǒngyuǎn","adv.","","","",""],
  ["用来","yònglái","v.","","","",""],
  ["用于","yòngyú","v.","","","",""],
  ["优点","yōudiǎn","n.","","","",""],
  ["幽默","yōumò","adj.","","","",""],
  ["优秀","yōuxiù","adj.","","","",""],
  ["由","yóu","prep.","","","",""],
  ["油","yóu","n.","","","",""],
  ["尤其","yóuqí","adv.","","","",""],
  ["游玩","yóuwán","v.","","","",""],
  ["由于","yóuyú","prep.","","","",""],
  ["友好","yǒuhǎo","adj.","","","",""],
  ["友情","yǒuqíng","n.","","","",""],
  ["有趣","yǒuqù","adj.","","","",""],
  ["有效","yǒuxiào","v.","","","",""],
  ["友谊","yǒuyì","n.","","","",""],
  ["有着","yǒuzhe","v.","","","",""],
  ["愉快","yúkuài","adj.","","","",""],
  ["于是","yúshì","conj.","","","",""],
  ["与","yǔ","prep.","","","",""],
  ["语法","yǔfǎ","n.","","","",""],
  ["预习","yùxí","v.","","","",""],
  ["原来","yuánlái","n.","","","",""],
  ["原谅","yuánliàng","v.","","","",""],
  ["原因","yuányīn","n.","","","",""],
  ["远离","yuǎnlí","v.","","","",""],
  ["院长","yuànzhǎng","n.","","","",""],
  ["院子","yuànzi","n.","","","",""],
  ["约","yuē","v.","","","",""],
  ["约会","yuēhuì","v.","","","",""],
  ["月饼","yuèbing","n.","","","",""],
  ["阅读","yuèdú","v.","","","",""],
  ["月份","yuèfèn","n.","","","",""],
  ["云","yún","n.","","","",""],
  ["允许","yǔnxǔ","v.","","","",""],
  ["杂志","zázhì","n.","","","",""],
  ["再次","zàicì","adv.","","","",""],
  ["再说","zàishuō","v.","","","",""],
  ["暂时","zànshí","adj.","","","",""],
  ["暂停","zàntíng","v.","","","",""],
  ["早餐","zǎocān","n.","","","",""],
  ["早晨","zǎochen","n.","","","",""],
  ["责任","zérèn","n.","","","",""],
  ["增加","zēngjiā","v.","","","",""],
  ["增长","zēngzhǎng","v.","","","",""],
  ["招聘","zhāopìn","v.","","","",""],
  ["着","zháo","v.","","","",""],
  ["着火","zháohuǒ","v.","","","",""],
  ["者","zhě","part.","","","",""],
  ["真正","zhēnzhèng","adj.","","","",""],
  ["整","zhěng","adj.","","","",""],
  ["整个","zhěnggè","adj.","","","",""],
  ["整理","zhěnglǐ","v.","","","",""],
  ["证","zhèng","n.","","","",""],
  ["正常","zhèngcháng","adj.","","","",""],
  ["正好","zhènghǎo","adj.","","","",""],
  ["证件","zhèngjiàn","n.","","","",""],
  ["证明","zhèngmíng","v.","","","",""],
  ["正确","zhèngquè","adj.","","","",""],
  ["正式","zhèngshì","adj.","","","",""],
  ["之","zhī","part.","","","",""],
  ["支持","zhīchí","v.","","","",""],
  ["支付","zhīfù","v.","","","",""],
  ["之后","zhīhòu","n.","","","",""],
  ["之间","zhījiān","n.","","","",""],
  ["之前","zhīqián","n.","","","",""],
  ["知识","zhīshi","n.","","","",""],
  ["之中","zhīzhōng","n.","","","",""],
  ["值","zhí","v.","","","",""],
  ["值得","zhídé","v.","","","",""],
  ["直接","zhíjiē","adj.","","","",""],
  ["植物","zhíwù","n.","","","",""],
  ["职业","zhíyè","n.","","","",""],
  ["指","zhǐ","v.","","","",""],
  ["指出","zhǐchū","v.","","","",""],
  ["只好","zhǐhǎo","adv.","","","",""],
  ["纸巾","zhǐjīn","n.","","","",""],
  ["质量","zhìliàng","n.","","","",""],
  ["至少","zhìshǎo","adv.","","","",""],
  ["中餐","zhōngcān","n.","","","",""],
  ["中年","zhōngnián","n.","","","",""],
  ["种","zhòng","v.","","","",""],
  ["重","zhòng","n.","","","",""],
  ["重点","zhòngdiǎn","n.","","","",""],
  ["重视","zhòngshì","v.","","","",""],
  ["周围","zhōuwéi","n.","","","",""],
  ["主意","zhǔyi","n.","","","",""],
  ["祝","zhù","v.","","","",""],
  ["祝贺","zhùhè","v.","","","",""],
  ["著名","zhùmíng","adj.","","","",""],
  ["专门","zhuānmén","adv.","","","",""],
  ["专业","zhuānyè","n.","","","",""],
  ["转","zhuǎn","v.","","","",""],
  ["转发","zhuǎnfā","v.","","","",""],
  ["转机","zhuǎnjī","v.","","","",""],
  ["赚","zhuàn","v.","","","",""],
  ["装","zhuāng","v.","","","",""],
  ["准","zhǔn","adj.","","","",""],
  ["准确","zhǔnquè","adj.","","","",""],
  ["准时","zhǔnshí","adj.","","","",""],
  ["资料","zīliào","n.","","","",""],
  ["仔细","zǐxì","adj.","","","",""],
  ["自","zì","prep.","","","",""],
  ["自然","zìrán","n.","","","",""],
  ["自习","zìxí","v.","","","",""],
  ["自信","zìxìn","v.","","","",""],
  ["自学","zìxué","v.","","","",""],
  ["总结","zǒngjié","v.","","","",""],
  ["租","zū","v.","","","",""],
  ["组","zǔ","n.","","","",""],
  ["最终","zuìzhōng","n.","","","",""],
  ["尊重","zūnzhòng","v.","","","",""],
  ["左右","zuǒyòu","n.","","","",""],
  ["座","zuò","n.","","","",""],
  ["做法","zuòfǎ","n.","","","",""],
  ["作家","zuòjiā","n.","","","",""],
  ["做梦","zuòmèng","v.","","","",""],
  ["作品","zuòpǐn","n.","","","",""],
  ["作为","zuòwéi","v.","","","",""],
  ["座位","zuòwèi","n.","","","",""],
  ["作文","zuòwén","v.","","","",""],
  ["作用","zuòyòng","n.","","","",""],
  ["作者","zuòzhě","n.","","","",""],
];
