// HSK 2 (Band 2) vocabulary — 200 words from the official 词汇大纲 (HSK 考试大纲).
// Hanzi, pinyin, and part-of-speech are taken directly from the syllabus PDF (序号 301–500).
// English glosses and example sentences are study aids authored for this course.
// Each entry: [hanzi, pinyin, pos, english, example_hanzi, example_pinyin, example_english]
window.BAND2_WORDS = [
  ["啊", "a", "part.", "ah; oh (particle)", "今天天气真好啊！", "Jīntiān tiānqì zhēn hǎo a！", "The weather is really nice today!"],
  ["爱好", "àihào", "v./n.", "hobby; to be fond of", "我的爱好是看书。", "Wǒ de àihào shì kàn shū.", "My hobby is reading."],
  ["白色", "báisè", "n.", "white (color)", "她穿了一件白色的衣服。", "Tā chuānle yí jiàn báisè de yīfu.", "She wore a white dress."],
  ["班", "bān", "n.", "class; team", "我们班有二十个学生。", "Wǒmen bān yǒu èrshí gè xuésheng.", "Our class has twenty students."],
  ["帮", "bāng", "v.", "to help", "你能帮我吗？", "Nǐ néng bāng wǒ ma？", "Can you help me?"],
  ["帮忙", "bāngmáng", "v.", "to help; do a favor", "谢谢你帮忙。", "Xièxie nǐ bāngmáng.", "Thank you for helping."],
  ["包", "bāo", "v./n./mw.", "bag; to wrap", "这个包很好看。", "Zhège bāo hěn hǎokàn.", "This bag is very pretty."],
  ["本子", "běnzi", "n.", "notebook", "我买了一个新本子。", "Wǒ mǎile yí gè xīn běnzi.", "I bought a new notebook."],
  ["比", "bǐ", "v./prep.", "compared to; than", "他比我高。", "Tā bǐ wǒ gāo.", "He is taller than me."],
  ["笔", "bǐ", "n.", "pen; writing brush", "这是我的笔。", "Zhè shì wǒ de bǐ.", "This is my pen."],
  ["别", "bié", "adv.", "don't; do not", "别走，等一下。", "Bié zǒu, děng yíxià.", "Don't go, wait a moment."],
  ["不错", "búcuò", "adj.", "not bad; pretty good", "这个菜很不错。", "Zhège cài hěn búcuò.", "This dish is pretty good."],
  ["不好意思", "bù hǎoyìsi", "adj.", "embarrassed; sorry", "不好意思，我来晚了。", "Bù hǎoyìsi, wǒ lái wǎn le.", "Sorry, I'm late."],
  ["长", "cháng", "adj.", "long", "这条路很长。", "Zhè tiáo lù hěn cháng.", "This road is very long."],
  ["车站", "chēzhàn", "n.", "station; bus stop", "车站在前面。", "Chēzhàn zài qiánmiàn.", "The station is up ahead."],
  ["出", "chū", "v.", "to go out; exit", "他出门了。", "Tā chū mén le.", "He went out."],
  ["出国", "chūguó", "v.", "to go abroad", "她明年要出国。", "Tā míngnián yào chūguó.", "She is going abroad next year."],
  ["出来", "chūlái", "v.", "to come out", "请你出来一下。", "Qǐng nǐ chūlái yíxià.", "Please come out for a moment."],
  ["出门", "chūmén", "v.", "to go out; leave home", "我每天八点出门。", "Wǒ měi tiān bā diǎn chūmén.", "I leave home at eight every day."],
  ["出去", "chūqù", "v.", "to go out", "我们出去走走吧。", "Wǒmen chūqù zǒuzou ba.", "Let's go out for a walk."],
  ["床", "chuáng", "n.", "bed", "这张床很大。", "Zhè zhāng chuáng hěn dà.", "This bed is very big."],
  ["词", "cí", "n.", "word", "这个词我不会。", "Zhège cí wǒ bú huì.", "I don't know this word."],
  ["次", "cì", "mw.", "time (occurrence)", "我去过两次北京。", "Wǒ qùguò liǎng cì Běijīng.", "I've been to Beijing twice."],
  ["从", "cóng", "prep.", "from", "我从家里来。", "Wǒ cóng jiā lǐ lái.", "I come from home."],
  ["从小", "cóngxiǎo", "adv.", "since childhood", "他从小喜欢音乐。", "Tā cóngxiǎo xǐhuan yīnyuè.", "He has loved music since childhood."],
  ["错", "cuò", "adj.", "wrong; mistaken", "你说错了。", "Nǐ shuō cuò le.", "You said it wrong."],
  ["打", "dǎ", "v.", "to hit; to play", "我们去打球吧。", "Wǒmen qù dǎ qiú ba.", "Let's go play ball."],
  ["打车", "dǎchē", "v.", "to take a taxi", "我们打车去吧。", "Wǒmen dǎchē qù ba.", "Let's take a taxi."],
  ["打开", "dǎkāi", "v.", "to open; turn on", "请打开窗户。", "Qǐng dǎkāi chuānghu.", "Please open the window."],
  ["但", "dàn", "conj.", "but; however", "我想去，但没有时间。", "Wǒ xiǎng qù, dàn méiyǒu shíjiān.", "I want to go, but I have no time."],
  ["但是", "dànshì", "conj.", "but; however", "他很累，但是很高兴。", "Tā hěn lèi, dànshì hěn gāoxìng.", "He is tired, but happy."],
  ["得", "de", "part.", "(structural particle)", "他跑得很快。", "Tā pǎo de hěn kuài.", "He runs very fast."],
  ["地", "de", "part.", "(adverbial particle)", "她高兴地笑了。", "Tā gāoxìng de xiào le.", "She smiled happily."],
  ["等", "děng", "v.", "to wait", "请等我一下。", "Qǐng děng wǒ yíxià.", "Please wait for me a moment."],
  ["地铁", "dìtiě", "n.", "subway; metro", "我坐地铁上班。", "Wǒ zuò dìtiě shàngbān.", "I take the subway to work."],
  ["点", "diǎn", "v.", "to order (food); o'clock", "我们点菜吧。", "Wǒmen diǎn cài ba.", "Let's order some food."],
  ["懂", "dǒng", "v.", "to understand", "我听懂了。", "Wǒ tīng dǒng le.", "I understood."],
  ["动", "dòng", "v.", "to move", "别动，等一下。", "Bié dòng, děng yíxià.", "Don't move, wait a moment."],
  ["饭馆", "fànguǎn", "n.", "restaurant", "这家饭馆很好吃。", "Zhè jiā fànguǎn hěn hǎochī.", "This restaurant is very tasty."],
  ["飞", "fēi", "v.", "to fly", "鸟在天上飞。", "Niǎo zài tiān shàng fēi.", "The bird flies in the sky."],
  ["高", "gāo", "adj./n.", "tall; high", "那座山很高。", "Nà zuò shān hěn gāo.", "That mountain is very high."],
  ["高中", "gāozhōng", "n.", "senior high school", "我哥哥在上高中。", "Wǒ gēge zài shàng gāozhōng.", "My older brother is in high school."],
  ["告诉", "gàosu", "v.", "to tell; inform", "请告诉我你的名字。", "Qǐng gàosu wǒ nǐ de míngzi.", "Please tell me your name."],
  ["个子", "gèzi", "n.", "height; build (of a person)", "他个子很高。", "Tā gèzi hěn gāo.", "He is very tall."],
  ["跟", "gēn", "prep./conj.", "with; and; to follow", "我跟你一起去。", "Wǒ gēn nǐ yìqǐ qù.", "I'll go with you."],
  ["公交车", "gōngjiāochē", "n.", "public bus", "我坐公交车回家。", "Wǒ zuò gōngjiāochē huí jiā.", "I take the bus home."],
  ["过", "guò", "v.", "to pass; to cross", "我们过马路吧。", "Wǒmen guò mǎlù ba.", "Let's cross the road."],
  ["过来", "guòlái", "v.", "to come over", "请你过来一下。", "Qǐng nǐ guòlái yíxià.", "Please come over here."],
  ["过年", "guònián", "v.", "to celebrate New Year", "我们回家过年。", "Wǒmen huí jiā guònián.", "We go home for the New Year."],
  ["过去", "guòqù", "v.", "to go over; the past", "他走过去了。", "Tā zǒu guòqù le.", "He walked over there."],
  ["过", "guo", "part.", "(experiential particle)", "我去过中国。", "Wǒ qùguo Zhōngguó.", "I have been to China."],
  ["还是", "háishi", "adv./conj.", "or; still; had better", "你喝茶还是喝水？", "Nǐ hē chá háishi hē shuǐ？", "Do you want tea or water?"],
  ["黑色", "hēisè", "n.", "black (color)", "我喜欢黑色的车。", "Wǒ xǐhuan hēisè de chē.", "I like black cars."],
  ["红茶", "hóngchá", "n.", "black tea", "我想喝红茶。", "Wǒ xiǎng hē hóngchá.", "I'd like to drink black tea."],
  ["红色", "hóngsè", "n.", "red (color)", "这朵花是红色的。", "Zhè duǒ huā shì hóngsè de.", "This flower is red."],
  ["后面", "hòumiàn", "n.", "behind; back", "学校在后面。", "Xuéxiào zài hòumiàn.", "The school is behind."],
  ["花", "huā", "v.", "to spend (money/time)", "我花了很多钱。", "Wǒ huāle hěn duō qián.", "I spent a lot of money."],
  ["花", "huā", "n./adj.", "flower", "这些花很漂亮。", "Zhèxiē huā hěn piàoliang.", "These flowers are very beautiful."],
  ["画", "huà", "v./n.", "to draw; painting", "她在画画。", "Tā zài huà huà.", "She is drawing a picture."],
  ["坏", "huài", "adj.", "bad; broken", "这个东西坏了。", "Zhège dōngxi huài le.", "This thing is broken."],
  ["回来", "huílái", "v.", "to come back", "他下午回来。", "Tā xiàwǔ huílái.", "He comes back in the afternoon."],
  ["回去", "huíqù", "v.", "to go back", "我想回去了。", "Wǒ xiǎng huíqù le.", "I want to go back."],
  ["机场", "jīchǎng", "n.", "airport", "机场很大。", "Jīchǎng hěn dà.", "The airport is very big."],
  ["机票", "jīpiào", "n.", "plane ticket", "我买了机票。", "Wǒ mǎi le jīpiào.", "I bought a plane ticket."],
  ["记得", "jìde", "v.", "to remember", "我记得他。", "Wǒ jìde tā.", "I remember him."],
  ["间", "jiān", "mw./n.", "measure word for rooms", "这是一间房子。", "Zhè shì yì jiān fángzi.", "This is a room."],
  ["教", "jiāo", "v.", "to teach", "老师教我们中文。", "Lǎoshī jiāo wǒmen Zhōngwén.", "The teacher teaches us Chinese."],
  ["教室", "jiàoshì", "n.", "classroom", "教室里有学生。", "Jiàoshì lǐ yǒu xuésheng.", "There are students in the classroom."],
  ["介绍", "jièshào", "v.", "to introduce", "我介绍一下我的朋友。", "Wǒ jièshào yíxià wǒ de péngyou.", "Let me introduce my friend."],
  ["进", "jìn", "v.", "to enter", "请进。", "Qǐng jìn.", "Please come in."],
  ["近", "jìn", "adj.", "near; close", "学校离我家很近。", "Xuéxiào lí wǒ jiā hěn jìn.", "The school is close to my home."],
  ["进来", "jìnlái", "v.", "to come in", "他走了进来。", "Tā zǒu le jìnlái.", "He walked in."],
  ["进去", "jìnqù", "v.", "to go in", "我们进去吧。", "Wǒmen jìnqù ba.", "Let's go in."],
  ["经常", "jīngcháng", "adv.", "often; frequently", "他经常运动。", "Tā jīngcháng yùndòng.", "He often exercises."],
  ["酒店", "jiǔdiàn", "n.", "hotel", "这家酒店很好。", "Zhè jiā jiǔdiàn hěn hǎo.", "This hotel is very good."],
  ["就", "jiù", "adv./prep.", "just; right away", "我就来。", "Wǒ jiù lái.", "I'm coming right away."],
  ["咖啡", "kāfēi", "n.", "coffee", "我喜欢喝咖啡。", "Wǒ xǐhuan hē kāfēi.", "I like drinking coffee."],
  ["开始", "kāishǐ", "v./n.", "to begin; start", "我们开始上课。", "Wǒmen kāishǐ shàngkè.", "We start class."],
  ["开学", "kāixué", "v.", "to start school", "九月开学。", "Jiǔyuè kāixué.", "School starts in September."],
  ["考", "kǎo", "v.", "to take an exam", "明天考数学。", "Míngtiān kǎo shùxué.", "Tomorrow we have a math exam."],
  ["考试", "kǎoshì", "v./n.", "exam; to test", "这次考试很难。", "Zhè cì kǎoshì hěn nán.", "This exam is very hard."],
  ["可能", "kěnéng", "adj./n./v.", "maybe; possible", "他可能不来。", "Tā kěnéng bù lái.", "He might not come."],
  ["裤子", "kùzi", "n.", "trousers; pants", "这条裤子很贵。", "Zhè tiáo kùzi hěn guì.", "These trousers are expensive."],
  ["快", "kuài", "adj./adv.", "fast; quick", "他跑得很快。", "Tā pǎo de hěn kuài.", "He runs very fast."],
  ["快乐", "kuàilè", "adj.", "happy; joyful", "祝你生日快乐。", "Zhù nǐ shēngrì kuàilè.", "Happy birthday to you."],
  ["快要", "kuàiyào", "adv.", "about to; soon", "火车快要开了。", "Huǒchē kuàiyào kāi le.", "The train is about to leave."],
  ["篮球", "lánqiú", "n.", "basketball", "我们打篮球。", "Wǒmen dǎ lánqiú.", "We play basketball."],
  ["累", "lèi", "adj./v.", "tired", "我今天很累。", "Wǒ jīntiān hěn lèi.", "I'm very tired today."],
  ["离", "lí", "v.", "away from; apart", "我家离公司很远。", "Wǒ jiā lí gōngsī hěn yuǎn.", "My home is far from the company."],
  ["里面", "lǐmiàn", "n.", "inside", "包里面有书。", "Bāo lǐmiàn yǒu shū.", "There are books inside the bag."],
  ["楼", "lóu", "n.", "building; floor", "我住在三楼。", "Wǒ zhù zài sān lóu.", "I live on the third floor."],
  ["路", "lù", "n.", "road; way", "这条路很长。", "Zhè tiáo lù hěn cháng.", "This road is very long."],
  ["路上", "lùshang", "n.", "on the way", "路上要小心。", "Lùshang yào xiǎoxīn.", "Be careful on the way."],
  ["旅游", "lǚyóu", "v.", "to travel", "我喜欢旅游。", "Wǒ xǐhuan lǚyóu.", "I like to travel."],
  ["绿茶", "lǜchá", "n.", "green tea", "我想喝绿茶。", "Wǒ xiǎng hē lǜchá.", "I want to drink green tea."],
  ["绿色", "lǜsè", "n./adj.", "green (color)", "我喜欢绿色。", "Wǒ xǐhuan lǜsè.", "I like the color green."],
  ["慢", "màn", "adj.", "slow", "他走得很慢。", "Tā zǒu de hěn màn.", "He walks very slowly."],
  ["没意思", "méi yìsi", "adj.", "boring; dull", "这本书没意思。", "Zhè běn shū méi yìsi.", "This book is boring."],
  ["每", "měi", "pron./adv.", "every; each", "我每天看书。", "Wǒ měi tiān kàn shū.", "I read every day."],
  ["门", "mén", "n.", "door", "请关门。", "Qǐng guān mén.", "Please close the door."],
  ["门口", "ménkǒu", "n.", "doorway; entrance", "他站在门口。", "Tā zhàn zài ménkǒu.", "He stands at the doorway."],
  ["门票", "ménpiào", "n.", "entrance ticket", "门票多少钱？", "Ménpiào duōshao qián?", "How much is the entrance ticket?"],
  ["面", "miàn", "v./n./mw.", "face; side; surface", "前面有一家店。", "Qiánmiàn yǒu yì jiā diàn.", "There is a shop ahead."],
  ["名", "míng", "n./mw.", "name; measure for people", "请写你的名。", "Qǐng xiě nǐ de míng.", "Please write your name."],
  ["拿", "ná", "v.", "to take; hold", "请拿这本书。", "Qǐng ná zhè běn shū.", "Please take this book."],
  ["那么", "nàme", "pron./conj.", "so; in that way", "他跑得那么快。", "Tā pǎo de nàme kuài.", "He runs so fast."],
  ["那样", "nàyàng", "pron.", "like that", "别那样做。", "Bié nàyàng zuò.", "Don't do it like that."],
  ["奶茶", "nǎichá", "n.", "milk tea", "我喜欢喝奶茶。", "Wǒ xǐhuan hē nǎichá.", "I like drinking milk tea."],
  ["奶奶", "nǎinai", "n.", "grandmother (paternal)", "我的奶奶很好。", "Wǒ de nǎinai hěn hǎo.", "My grandmother is very kind."],
  ["男孩儿", "nánháir", "n.", "boy", "那个男孩儿很高。", "Nàge nánháir hěn gāo.", "That boy is very tall."],
  ["鸟", "niǎo", "n.", "bird", "树上有一只鸟。", "Shù shàng yǒu yì zhī niǎo.", "There is a bird in the tree."],
  ["女孩儿", "nǚháir", "n.", "girl", "那个女孩儿很漂亮。", "Nàge nǚháir hěn piàoliang.", "That girl is very pretty."],
  ["旁边", "pángbiān", "n.", "beside; next to", "他坐在我旁边。", "Tā zuò zài wǒ pángbiān.", "He sits next to me."],
  ["跑", "pǎo", "v.", "to run", "他跑得很快。", "Tā pǎo de hěn kuài.", "He runs very fast."],
  ["跑步", "pǎobù", "v.", "to jog; run", "我每天跑步。", "Wǒ měi tiān pǎobù.", "I jog every day."],
  ["票", "piào", "n.", "ticket", "我买了两张票。", "Wǒ mǎi le liǎng zhāng piào.", "I bought two tickets."],
  ["妻子", "qīzi", "n.", "wife", "他的妻子是老师。", "Tā de qīzi shì lǎoshī.", "His wife is a teacher."],
  ["起来", "qǐlái", "v.", "to get up; rise", "他早上六点起来。", "Tā zǎoshang liù diǎn qǐlái.", "He gets up at six in the morning."],
  ["前面", "qiánmiàn", "n.", "in front; ahead", "前面有一个公园。", "Qiánmiàn yǒu yí ge gōngyuán.", "There is a park ahead."],
  ["晴", "qíng", "adj.", "sunny; clear", "今天天气很晴。", "Jīntiān tiānqì hěn qíng.", "The weather is sunny today."],
  ["球", "qiú", "n.", "ball", "他们在踢球。", "Tāmen zài tī qiú.", "They are playing ball."],
  ["让", "ràng", "v./prep.", "to let; allow", "妈妈让我休息。", "Māma ràng wǒ xiūxi.", "Mom lets me rest."],
  ["肉", "ròu", "n.", "meat", "我不吃肉。", "Wǒ bù chī ròu.", "I don't eat meat."],
  ["商场", "shāngchǎng", "n.", "shopping mall", "商场里人很多。", "Shāngchǎng lǐ rén hěn duō.", "There are many people in the mall."],
  ["上来", "shànglái", "v.", "to come up", "请上来。", "Qǐng shànglái.", "Please come up."],
  ["上面", "shàngmiàn", "n.", "above; on top", "桌子上面有书。", "Zhuōzi shàngmiàn yǒu shū.", "There are books on top of the table."],
  ["上去", "shàngqù", "v.", "to go up", "我们上去看看。", "Wǒmen shàngqù kànkan.", "Let's go up and take a look."],
  ["上网", "shàngwǎng", "v.", "to go online", "我喜欢上网。", "Wǒ xǐhuan shàngwǎng.", "I like to go online."],
  ["身体", "shēntǐ", "n.", "body; health", "他身体很好。", "Tā shēntǐ hěn hǎo.", "He is in good health."],
  ["生日", "shēngrì", "n.", "birthday", "今天是我的生日。", "Jīntiān shì wǒ de shēngrì.", "Today is my birthday."],
  ["时", "shí", "n./mw.", "time; hour", "上课时要安静。", "Shàngkè shí yào ānjìng.", "Be quiet during class."],
  ["事情", "shìqing", "n.", "matter; affair", "我有一件事情。", "Wǒ yǒu yí jiàn shìqing.", "I have a matter to deal with."],
  ["手", "shǒu", "n.", "hand", "请洗手。", "Qǐng xǐ shǒu.", "Please wash your hands."],
  ["手表", "shǒubiǎo", "n.", "wristwatch", "这块手表很贵。", "Zhè kuài shǒubiǎo hěn guì.", "This wristwatch is expensive."],
  ["书包", "shūbāo", "n.", "schoolbag", "我的书包很重。", "Wǒ de shūbāo hěn zhòng.", "My schoolbag is very heavy."],
  ["舒服", "shūfu", "adj.", "comfortable", "这张床很舒服。", "Zhè zhāng chuáng hěn shūfu.", "This bed is very comfortable."],
  ["送", "sòng", "v.", "to give; deliver", "我送你回家。", "Wǒ sòng nǐ huí jiā.", "I'll see you home."],
  ["虽然", "suīrán", "conj.", "although", "虽然下雨，但是不冷。", "Suīrán xià yǔ, dànshì bù lěng.", "Although it's raining, it's not cold."],
  ["所以", "suǒyǐ", "conj.", "therefore; so", "他病了，所以没来。", "Tā bìng le, suǒyǐ méi lái.", "He was sick, so he didn't come."],
  ["疼", "téng", "adj./v.", "to ache; sore", "我的头很疼。", "Wǒ de tóu hěn téng.", "My head hurts."],
  ["踢", "tī", "v.", "to kick", "他喜欢踢足球。", "Tā xǐhuān tī zúqiú.", "He likes to play soccer."],
  ["题", "tí", "n.", "problem; question", "这道题很难。", "Zhè dào tí hěn nán.", "This problem is very hard."],
  ["条", "tiáo", "mw.", "measure word for long things", "我买了一条鱼。", "Wǒ mǎi le yì tiáo yú.", "I bought a fish."],
  ["跳舞", "tiàowǔ", "v.", "to dance", "她在跳舞。", "Tā zài tiàowǔ.", "She is dancing."],
  ["头", "tóu", "n.", "head", "我的头有点疼。", "Wǒ de tóu yǒudiǎn téng.", "My head hurts a little."],
  ["外国", "wàiguó", "n.", "foreign country", "他想去外国旅行。", "Tā xiǎng qù wàiguó lǚxíng.", "He wants to travel abroad."],
  ["外面", "wàimiàn", "n.", "outside", "外面在下雨。", "Wàimiàn zài xià yǔ.", "It is raining outside."],
  ["完", "wán", "v.", "to finish", "我吃完饭了。", "Wǒ chī wán fàn le.", "I have finished eating."],
  ["万", "wàn", "num.", "ten thousand", "这本书卖一万本。", "Zhè běn shū mài yí wàn běn.", "This book sold ten thousand copies."],
  ["往", "wǎng", "v./prep.", "toward; to go to", "往前走就到了。", "Wǎng qián zǒu jiù dào le.", "Walk forward and you'll arrive."],
  ["网上", "wǎngshang", "n.", "online; on the internet", "我在网上买东西。", "Wǒ zài wǎngshang mǎi dōngxi.", "I shop online."],
  ["忘", "wàng", "v.", "to forget", "我忘了他的名字。", "Wǒ wàng le tā de míngzi.", "I forgot his name."],
  ["位", "wèi", "mw.", "measure word for people (polite)", "来了三位客人。", "Lái le sān wèi kèrén.", "Three guests have arrived."],
  ["为什么", "wèi shénme", "pron.", "why", "你为什么不来？", "Nǐ wèi shénme bù lái?", "Why don't you come?"],
  ["希望", "xīwàng", "v.", "to hope", "我希望你成功。", "Wǒ xīwàng nǐ chénggōng.", "I hope you succeed."],
  ["洗", "xǐ", "v.", "to wash", "我要洗手。", "Wǒ yào xǐ shǒu.", "I want to wash my hands."],
  ["洗手间", "xǐshǒujiān", "n.", "restroom; bathroom", "洗手间在哪儿？", "Xǐshǒujiān zài nǎr?", "Where is the restroom?"],
  ["下来", "xiàlái", "v.", "to come down", "请你下来一下。", "Qǐng nǐ xiàlái yíxià.", "Please come down for a moment."],
  ["下面", "xiàmiàn", "n.", "below; underneath", "猫在桌子下面。", "Māo zài zhuōzi xiàmiàn.", "The cat is under the table."],
  ["下去", "xiàqù", "v.", "to go down", "我们走下去吧。", "Wǒmen zǒu xiàqù ba.", "Let's walk down."],
  ["小孩儿", "xiǎoháir", "n.", "child", "这个小孩儿很可爱。", "Zhège xiǎoháir hěn kě'ài.", "This child is very cute."],
  ["小时候", "xiǎoshíhou", "n.", "childhood", "我小时候住在这里。", "Wǒ xiǎoshíhou zhù zài zhèlǐ.", "I lived here in my childhood."],
  ["笑", "xiào", "v.", "to laugh; to smile", "她笑得很开心。", "Tā xiào de hěn kāixīn.", "She laughs happily."],
  ["姓", "xìng", "n./v.", "surname; to be surnamed", "我姓王。", "Wǒ xìng Wáng.", "My surname is Wang."],
  ["姓名", "xìngmíng", "n.", "full name", "请写下你的姓名。", "Qǐng xiě xià nǐ de xìngmíng.", "Please write down your full name."],
  ["颜色", "yánsè", "n.", "color", "你喜欢什么颜色？", "Nǐ xǐhuān shénme yánsè?", "What color do you like?"],
  ["眼睛", "yǎnjing", "n.", "eye", "她的眼睛很大。", "Tā de yǎnjing hěn dà.", "Her eyes are very big."],
  ["药", "yào", "n.", "medicine", "你要按时吃药。", "Nǐ yào ànshí chī yào.", "You should take your medicine on time."],
  ["药店", "yàodiàn", "n.", "pharmacy", "前面有一家药店。", "Qiánmiàn yǒu yì jiā yàodiàn.", "There is a pharmacy up ahead."],
  ["爷爷", "yéye", "n.", "grandfather (paternal)", "我爷爷今年八十岁。", "Wǒ yéye jīnnián bāshí suì.", "My grandfather is eighty this year."],
  ["一会儿", "yíhuìr", "num.+mw.", "a little while", "请等我一会儿。", "Qǐng děng wǒ yíhuìr.", "Please wait for me a moment."],
  ["已经", "yǐjīng", "adv.", "already", "他已经走了。", "Tā yǐjīng zǒu le.", "He has already left."],
  ["一起", "yìqǐ", "adv.", "together", "我们一起吃饭吧。", "Wǒmen yìqǐ chī fàn ba.", "Let's eat together."],
  ["意思", "yìsi", "n.", "meaning", "这个词是什么意思？", "Zhège cí shì shénme yìsi?", "What does this word mean?"],
  ["阴", "yīn", "adj.", "cloudy; overcast", "今天天气很阴。", "Jīntiān tiānqì hěn yīn.", "The weather is very cloudy today."],
  ["因为", "yīnwèi", "prep./conj.", "because", "因为下雨，我没去。", "Yīnwèi xià yǔ, wǒ méi qù.", "I didn't go because it rained."],
  ["游", "yóu", "v.", "to swim", "他游得很快。", "Tā yóu de hěn kuài.", "He swims very fast."],
  ["游泳", "yóuyǒng", "v.", "to swim", "我每天去游泳。", "Wǒ měitiān qù yóuyǒng.", "I go swimming every day."],
  ["有意思", "yǒu yìsi", "adj.", "interesting", "这本书很有意思。", "Zhè běn shū hěn yǒu yìsi.", "This book is very interesting."],
  ["有时", "yǒushí", "adv.", "sometimes", "我有时去公园。", "Wǒ yǒushí qù gōngyuán.", "I sometimes go to the park."],
  ["右", "yòu", "n.", "right (direction)", "请向右转。", "Qǐng xiàng yòu zhuǎn.", "Please turn right."],
  ["右边", "yòubian", "n.", "right side", "银行在右边。", "Yínháng zài yòubian.", "The bank is on the right side."],
  ["鱼", "yú", "n.", "fish", "这条鱼很新鲜。", "Zhè tiáo yú hěn xīnxiān.", "This fish is very fresh."],
  ["远", "yuǎn", "adj.", "far", "学校离这儿很远。", "Xuéxiào lí zhèr hěn yuǎn.", "The school is far from here."],
  ["运动", "yùndòng", "v./n.", "sports; to exercise", "我喜欢做运动。", "Wǒ xǐhuān zuò yùndòng.", "I like to do sports."],
  ["站", "zhàn", "v.", "to stand", "请站起来。", "Qǐng zhàn qǐlái.", "Please stand up."],
  ["丈夫", "zhàngfu", "n.", "husband", "她的丈夫是医生。", "Tā de zhàngfu shì yīshēng.", "Her husband is a doctor."],
  ["这么", "zhème", "pron.", "so; like this", "你怎么这么忙？", "Nǐ zěnme zhème máng?", "Why are you so busy?"],
  ["这样", "zhèyàng", "pron.", "like this; this way", "你不应该这样做。", "Nǐ bù yīnggāi zhèyàng zuò.", "You shouldn't do it this way."],
  ["着", "zhe", "part.", "verbal aspect particle", "他笑着说话。", "Tā xiào zhe shuōhuà.", "He spoke while smiling."],
  ["正", "zhèng", "adv./adj.", "just; in the middle of", "我正在吃饭。", "Wǒ zhèng zài chī fàn.", "I am just eating."],
  ["周", "zhōu", "n./mw.", "week", "这周我很忙。", "Zhè zhōu wǒ hěn máng.", "I am very busy this week."],
  ["准备", "zhǔnbèi", "v.", "to prepare", "我在准备考试。", "Wǒ zài zhǔnbèi kǎoshì.", "I am preparing for the exam."],
  ["自己", "zìjǐ", "pron.", "oneself", "我自己做饭。", "Wǒ zìjǐ zuò fàn.", "I cook by myself."],
  ["走", "zǒu", "v.", "to walk; to go", "我们走吧。", "Wǒmen zǒu ba.", "Let's go."],
  ["走路", "zǒulù", "v.", "to walk", "我每天走路上班。", "Wǒ měitiān zǒulù shàngbān.", "I walk to work every day."],
  ["足球", "zúqiú", "n.", "soccer; football", "他们在踢足球。", "Tāmen zài tī zúqiú.", "They are playing soccer."],
  ["最", "zuì", "adv.", "most", "这是最好的办法。", "Zhè shì zuì hǎo de bànfǎ.", "This is the best way."],
  ["左", "zuǒ", "n.", "left (direction)", "请向左转。", "Qǐng xiàng zuǒ zhuǎn.", "Please turn left."],
  ["左边", "zuǒbian", "n.", "left side", "商店在左边。", "Shāngdiàn zài zuǒbian.", "The store is on the left side."],
];
